xyflow/xyflow

package.json
=> chore(pkg): export types

README.md, cypress/integration/flow/empty.spec.js, cypress/integration/flow/inactive.spec.js, example/src/Rich/index.js, src/components/Edges/wrapEdge.tsx, src/components/Nodes/wrapNode.tsx, src/style.css
=> refactor(inactivemode): no pointer events for nodes and edges 

src/store/index.ts, src/types/index.ts
```
fitView({ padding: 10 })
fitView({})
```
* Change readme (this PR)
* Change the type signature
=> README: fitView needs an argument

src/container/GraphView/index.tsx
Will call `setOnConnect` if function passed as `onConnect` changes.
There are other ways to fix #372. Feel free to close this proposal to fix the issue and use another solution instead :)
Closes #372
=> Bugfix: Update onConnect

README.md, example/src/Basic/index.js, example/src/CustomNode/index.js, example/src/Edges/index.js, example/src/Empty/index.js, example/src/Interaction/index.js, example/src/Overview/index.js, example/src/Provider/index.js, example/src/Validation/index.js, src/components/Edges/wrapEdge.tsx, src/components/Handle/BaseHandle.tsx, src/components/Nodes/wrapNode.tsx, src/container/EdgeRenderer/index.tsx, src/container/GraphView/index.tsx, src/container/NodeRenderer/index.tsx, src/container/ReactFlow/index.tsx, src/types/index.ts
Addresses #399
Expose `MouseEvent` in the following functions:
- `onElementClick`
- `onNodeDragStart`
- `onNodeDragStop`
- `onConnectStart`
- `onConnectStop`
- `onPaneClick`
=> Add event handlers

src/container/ReactFlow/index.tsx
Forgot to add this type definition at the top level interface.
=> Add Type Definition for onPaneClick

example/src/Interaction/index.js, src/container/GraphView/index.tsx, src/container/ReactFlow/index.tsx
Add `onPaneContextMenu` with captured event
=> Add onPaneContextMenu

README.md, example/src/Provider/index.js, src/container/GraphView/index.tsx, src/store/hooks.ts, src/utils/graph.ts
=> fix(onLoad): use project and getElements inside with ReactFlowProvider 

README.md
=> syntax error on in example code fix 

example/src/Interaction/index.js, src/container/GraphView/index.tsx, src/container/ReactFlow/index.tsx
- add the possibility to listen to the onWheel event
- add event handler to interaction demo
#480
=> feat: add onPaneScroll event handler

src/hooks/useElementUpdater.ts
Fix for issue https://github.com/wbkd/react-flow/issues/462
=> Added support for Node and Edge type updates

README.md, src/additional-components/Controls/index.tsx
This PR adds optional callbacks to the `Control` component for when the buttons are clicked. 
I also added the callback descriptions to the README.
=> feat(control): add optional callbacks

README.md, cypress/integration/flow/basic.spec.js, cypress/integration/flow/controls.spec.js, cypress/integration/flow/empty.spec.js, cypress/integration/flow/interaction.spec.js, cypress/integration/flow/minimap.spec.js, example/src/Overview/index.js, src/components/UserSelection/index.tsx, src/container/FlowRenderer/index.tsx, src/container/GraphView/index.tsx, src/hooks/useD3Zoom.ts, src/style.css
=> Zoom handling

website/src/markdown/docs/getting-started/index.md
it cost me an hour to fix this in my simple test. ;)
=> made example programmer friendlier

example/src/CustomNode/ColorSelectorNode.js, example/src/CustomNode/index.js, example/src/Validation/index.js, src/components/Handle/BaseHandle.tsx, src/components/Nodes/utils.ts, src/container/EdgeRenderer/index.tsx, src/types/index.ts, src/utils/graph.ts
Cleanup of the work done by @jasonpul.
=> Added support for multiple handles

example/package-lock.json, example/src/CustomNode/ColorSelectorNode.js, example/src/CustomNode/index.js, example/src/Validation/index.js, example/src/index.js, package-lock.json, src/components/Handle/BaseHandle.tsx, src/components/Nodes/utils.ts, src/container/EdgeRenderer/index.tsx, src/types/index.ts, src/utils/graph.ts
Hello Moritz,
I started using your react-flow library recently. It's great! thanks for releasing it for people like me to use. I was playing around with the validation example you created and had a few ideas for improvements. I think this is a complete list of what my pull request changes:
- restricts connections to target-to-source or source-to-target only. source-to-source and target-to-target connection attempts are ignored. I'm not sure when there's a use case for those types of connections.
- disallows non-unique edges. addEdge now checks to see if the requested connection (source node & handle to target node & handle) already exists.
- I broke out handle-Id into it's own attribute (data-handleid). I needed to do this to implement the unique-edges-only functionality and keep the …
=> Connection validation

nocss/package.json, package.json
Fixes Distribute package without default styles #834
=> feat(npm): nocss package entry point

src/additional-components/Controls/index.tsx, src/hooks/useZoomPanHelper.ts, src/types/index.ts
=> feat(fitView): added option to exclude hidden nodes

src/components/Nodes/wrapNode.tsx, src/components/NodesSelection/index.tsx
fix for https://github.com/wbkd/react-flow/issues/912
=> fix(updateNodePosDiff): added missing isDragging: true in action payload

src/components/Nodes/wrapNode.tsx, src/container/GraphView/index.tsx, src/container/NodeRenderer/index.tsx, src/container/ReactFlow/index.tsx, src/types/index.ts
We have a custom use case for node double click events, wondering if you're open to supporting it. No worries if not :)
=> Support element double click handler.

src/components/Edges/wrapEdge.tsx, src/container/EdgeRenderer/index.tsx, src/container/GraphView/index.tsx, src/container/ReactFlow/index.tsx, src/container/ZoomPane/index.tsx, src/types/index.ts
Hello, our team really needed this feature, so I implemented it.
=> onEdgeDoubleClick support

example/src/index.css
=> Made example section discoverable on widescreen monitors

src/components/Nodes/wrapNode.tsx, src/container/NodeRenderer/index.tsx, src/types/index.ts
=> Add optional node dragHandle prop as DraggableCore handle.

src/hooks/useZoomPanHelper.ts
=> fix(zoomPanHelper): fix missing duration on transform #1883

src/components/StoreUpdater/index.tsx, src/types/component-props.ts, src/types/general.ts
Refs: https://github.com/wbkd/react-flow/pull/1555#issuecomment-1043150079, e011375c3d25765c56bb790de4a216ca0bcfabfa
=> fix: export type OnNodesDelete and OnEdgesDelete

src/hooks/useNodesEdgesState.ts
Type incorrect
Refs: https://github.com/wbkd/react-flow/pull/1555/commits/414d7ec993ed66d4ceb0c521176f94128eec6eef
Upstream: #1555
=> fix: type error

src/components/Nodes/wrapNode.tsx
should close https://github.com/wbkd/react-flow/issues/1985, but I'm not sure adding more logic and making the code harder to debug will be the right choice.
=> fix multiSelection when selectNodesOnDrag is false

package.json
=> fix(pkg): add css files to the exports

example/src/Overview/index.tsx, src/hooks/useDrag/index.ts, src/hooks/useDrag/utils.ts, src/store/index.ts, src/store/utils.ts, src/types/changes.ts, src/types/nodes.ts, src/utils/changes.ts
=> fix(subflows): use abs positions for internal calculations

examples/nextjs/package.json, examples/nextjs/tsconfig.json, package.json, packages/background/package.json, packages/background/tsconfig.json, packages/controls/package.json, packages/controls/tsconfig.json, packages/core/package.json, packages/core/tsconfig.json, packages/minimap/package.json, packages/minimap/tsconfig.json, packages/reactflow/package.json, packages/reactflow/tsconfig.json, tooling/tsconfig/base.json, tooling/tsconfig/package.json, tooling/tsconfig/react.json, tsconfig.json, yarn.lock
refactor(tsconfigs): extend from base tsconfig, add tsconfig for every package
=> Refactor: tsconfigs

examples/vite-app/package.json, examples/vite-app/src/App/index.tsx, examples/vite-app/src/examples/CancelConnection/Timer.module.css, examples/vite-app/src/examples/CancelConnection/Timer.tsx, examples/vite-app/src/examples/CancelConnection/data.ts, examples/vite-app/src/examples/CancelConnection/hooks/useCountdown.ts, examples/vite-app/src/examples/CancelConnection/index.tsx, packages/core/src/types/general.ts, pnpm-lock.yaml
- Example added for `cancelConnection` method in `useStore`
- One typing issue fixed
- `classcat` added to `examples`
=> feat(examples): example added for cancelConnection

.changeset/small-walls-enjoy.md, packages/core/src/components/ConnectionLine/index.tsx
=> fix(updatable-edge): fix disappearing connection line for loose flows

examples/vite-app/src/examples/NodeResizer/NodeResizerNode.tsx, packages/node-resizer/CHANGELOG.md, packages/node-resizer/package.json, packages/node-resizer/src/NodeResizer.tsx, packages/node-resizer/src/ResizeControl.tsx, packages/node-resizer/src/types.ts
```ts
type ResizeEventParams = {
x: number;
y: number;
width: number;
height: number;
};
type NodeResizerProps = {
nodeId?: string;
color?: string;
handleClassName?: string;
handleStyle?: CSSProperties;
lineClassName?: string;
lineStyle?: CSSProperties;
isVisible?: boolean;
minWidth?: number;
minHeight?: number;
onResizeStart?: (event: ResizeDragEvent, params: ResizeEventParams) => void;
onResize?: (event: ResizeDragEvent, params: ResizeEventParams) => void;
onResizeEnd?: (event: ResizeDragEvent, params: ResizeEventParams) => void;
};
```
=> feat(resizer): add resize event handlers

.changeset/purple-mails-kneel.md, packages/core/src/container/ZoomPane/index.tsx, packages/core/src/store/index.ts, packages/minimap/src/MiniMap.tsx
=> fix(minimap): use translateExtent on pan

README.md
I transferred useUndoable to my personal account; this corrects the link to it in the README 👍
=> docs: Update useUndoable link

packages/core/src/components/Handle/handler.ts, packages/core/src/components/Handle/index.tsx, packages/core/src/components/Handle/utils.ts, packages/core/src/container/ReactFlow/index.tsx, packages/core/src/hooks/useDrag/index.ts, packages/core/src/store/index.ts, packages/core/src/store/initialState.ts, packages/core/src/types/component-props.ts, packages/core/src/types/general.ts, packages/core/src/utils/graph.ts
Adds a new prop `connectionRadius` - this makes it possible to adjust the radius around a handle where you can connect an edge. This PR makes it easier to connect nodes because you don't need to drop the connection line above a handle but only close to it.
https://user-images.githubusercontent.com/2857535/213244354-4f19de23-21c9-4013-9bf9-718d40ddaf32.mov
=> Connection Radius

.changeset/hungry-eagles-turn.md, examples/vite-app/package.json, packages/core/src/components/Edges/wrapEdge.tsx, packages/core/src/components/Handle/handler.ts, packages/core/src/components/Handle/index.tsx, packages/core/src/components/Handle/utils.ts, packages/core/src/container/Pane/index.tsx, packages/core/src/hooks/useDrag/index.ts, packages/core/src/store/index.ts, packages/core/src/types/component-props.ts, packages/core/src/types/edges.ts, packages/core/src/types/general.ts, packages/core/src/utils/index.ts
This enables the user to connect two nodes on a touch screen without using click connect.
=> Feat: touch connect

.changeset/shaggy-suits-watch.md, examples/vite-app/src/App/index.tsx, examples/vite-app/src/examples/EasyConnect/CustomConnectionLine.tsx, examples/vite-app/src/examples/EasyConnect/CustomNode.tsx, examples/vite-app/src/examples/EasyConnect/FloatingEdge.tsx, examples/vite-app/src/examples/EasyConnect/index.tsx, examples/vite-app/src/examples/EasyConnect/style.css, examples/vite-app/src/examples/EasyConnect/utils.tsx, examples/vite-app/src/examples/Validation/index.tsx, packages/background/CHANGELOG.md, packages/background/package.json, packages/controls/CHANGELOG.md, packages/controls/package.json, packages/core/CHANGELOG.md, packages/core/package.json, packages/core/src/components/Handle/handler.ts, packages/core/src/components/Handle/index.tsx, packages/core/src/components/Handle/utils.ts, packages/minimap/CHANGELOG.md, packages/minimap/package.json, packages/node-toolbar/CHANGELOG.md, packages/node-toolbar/package.json, packages/reactflow/CHANGELOG.md, packages/reactflow/package.json
=> refactor(handle): first check element below then connection radius

.changeset/four-dancers-call.md, packages/core/src/components/Handle/handler.ts
=> fix(connections): fix connections with handles bigger than connec radius

.changeset/witty-eagles-type.md, packages/core/src/utils/index.ts
=> refactor(use-key-press): handle modifier keys + inputs

.changeset/dirty-tools-switch.md, examples/vite-app/src/examples/EasyConnect/CustomNode.tsx, examples/vite-app/src/examples/EasyConnect/style.css, packages/core/src/components/Handle/handler.ts, packages/core/src/components/Handle/index.tsx, packages/core/src/components/Handle/utils.ts
=> refactor(handles): reduce re-renderings, handles on top of each other 

examples/vite-app/src/examples/NodeToolbar/CustomNode.tsx, examples/vite-app/src/examples/NodeToolbar/index.tsx, packages/node-toolbar/src/NodeToolbar.tsx, packages/node-toolbar/src/types.ts
adds the ability to align the toolbar to the start or end of the node's dimensions
=> feat(node-toolbar): add align prop

.changeset/chilled-insects-call.md, .github/ISSUE_TEMPLATE/bug_report.yml, CONTRIBUTING.md, packages/core/src/hooks/useEdges.ts, packages/core/src/hooks/useNodes.ts
=> fix(useNodes,useEdges): prevent re-renderings

packages/node-resizer/src/ResizeControl.tsx
Fixes https://github.com/wbkd/react-flow/issues/3119
=> [Bugfix] Include onResize/onResizeStart/onResizeEnd in the list of useEffect dependencies

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/feature_request.yml, packages/reactflow/README.md
- adding note about Svelte and feature freeze to README, along with link for more details
- adding note about xyflow branch to Feature Request
- remove deprecated bug report message
=> chore(copy): template change

.changeset/chilled-insects-call.md, .changeset/chilly-months-fetch.md, .changeset/funny-penguins-tickle.md, .changeset/little-books-listen.md, .changeset/quick-mice-marry.md, .changeset/twelve-deers-live.md, .changeset/wet-laws-nail.md, .changeset/wise-needles-kneel.md, .github/ISSUE_TEMPLATE/bug_report.yml, CONTRIBUTING.md, examples/vite-app/src/examples/Basic/index.tsx, examples/vite-app/src/examples/Subflow/index.tsx, packages/background/CHANGELOG.md, packages/background/package.json, packages/controls/CHANGELOG.md, packages/controls/package.json, packages/core/CHANGELOG.md, packages/core/package.json, packages/minimap/CHANGELOG.md, packages/minimap/package.json, packages/node-resizer/CHANGELOG.md, packages/node-resizer/package.json, packages/node-toolbar/CHANGELOG.md, packages/node-toolbar/package.json, packages/reactflow/CHANGELOG.md, packages/reactflow/package.json
* fix(node-resizer): add onResize/onResizeStart/onResizeEnd to useEffect deps thanks @goliney
* fix(core): use valid handles in proximity to determine closest handle thanks @bcakmakoglu
* refactor(minimap): improve performance for flows with lots of nodes that use the minimap component
* refactor(core): adjust elevateEdgesOnSelect so that it works like elevateNOdesOnSelect closes #3094
=> Next release

.changeset/serious-pillows-wash.md, examples/vite-app/src/examples/EdgeRouting/index.tsx, packages/core/src/components/Edges/SmoothStepEdge.tsx
=> fix(smooth-edge): vertically or horizontally aligned nodes closes #3205

packages/core/src/utils/index.ts
Fixes https://github.com/wbkd/react-flow/issues/3315
=> Fix navigator being used on server-side rendering

.changeset/calm-mugs-relax.md, packages/core/src/hooks/useGlobalKeyHandler.ts, packages/core/src/hooks/useKeyPress.ts
=> refactor(nodes): dont delete nodes when user focuses input and presses modifier

packages/core/src/index.ts, packages/core/src/utils/changes.ts
Hey,
I tried to use this logic in a custom data store but it's not exposed. 
It would be handy instead of copy pasting the code.
lmk
=> fix(core): export handleParentExpand

.changeset/green-guests-enjoy.md, packages/core/src/hooks/useDrag/utils.ts, packages/core/src/types/nodes.ts
=> refactor(node): make expandParent compatible with extent parent

.changeset/few-lizards-carry.md, packages/core/src/components/Nodes/wrapNode.tsx
=> fix(selection): select nodes on click when nodeDragThreshold > 0

packages/svelte/src/lib/container/SvelteFlow/SvelteFlow.svelte
=> fix(svelte) resizing updates width & height in the store correctly

examples/svelte/src/routes/usesvelteflow/Sidebar.svelte, packages/svelte/src/lib/hooks/useSvelteFlow.ts
=> feat(svelte) added toObject() on useSvelteFlow

.changeset/dry-buttons-end.md, packages/core/src/hooks/useReactFlow.ts
nodeOrRect.width calls to nodeRect.width calls closes #3554
=> fix: intersection helpers

examples/react/src/examples/UseOnSelectionChange/index.tsx, packages/react/src/components/SelectionListener/index.tsx, packages/react/src/hooks/useOnSelectionChange.ts, packages/react/src/store/initialState.ts, packages/react/src/types/store.ts, pnpm-lock.yaml
Solves: [ Support Mutiple useOnSelectionChange Hook #2980 ](https://github.com/wbkd/react-flow/issues/2980)
=> feat(react): Support mutiple useOnSelectionChange hook subscribers

.changeset/spotty-balloons-ring.md, examples/vite-app/src/examples/DragNDrop/index.tsx, examples/vite-app/src/examples/Undirectional/index.tsx, examples/vite-app/src/examples/UseReactFlow/index.tsx, examples/vite-app/src/examples/UseUpdateNodeInternals/index.tsx, packages/background/CHANGELOG.md, packages/background/package.json, packages/controls/CHANGELOG.md, packages/controls/package.json, packages/core/CHANGELOG.md, packages/core/package.json, packages/core/src/hooks/useViewportHelper.ts, packages/core/src/types/general.ts, packages/minimap/CHANGELOG.md, packages/minimap/package.json, packages/node-resizer/CHANGELOG.md, packages/node-resizer/package.json, packages/node-toolbar/CHANGELOG.md, packages/node-toolbar/package.json, packages/reactflow/CHANGELOG.md, packages/reactflow/package.json
=> fix(react-flow-instance): add screenToFlow and flowToScreen types

examples/react/src/examples/ColorMode/index.tsx, examples/svelte/src/routes/examples/customnode/+page.svelte, packages/react/src/additional-components/Background/Background.tsx, packages/react/src/additional-components/MiniMap/MiniMap.tsx, packages/svelte/src/lib/plugins/Background/Background.svelte, packages/svelte/src/lib/plugins/Controls/ControlButton.svelte, packages/svelte/src/lib/plugins/Minimap/Minimap.svelte, packages/system/src/styles/base.css, packages/system/src/styles/init.css, packages/system/src/styles/style.css
This PR prefixes all css variables with "xy" and fixes a bug with the Background "bgColor" prop
=> CSS: prefix css vars with "xy"

examples/astro-xyflow/src/components/ReactFlowExample/CustomNode.tsx, packages/react/src/components/StoreUpdater/index.tsx
Thanks to this PR from @iamakulov #3677 we could refactor the `StoreUpdater` to make it easier to understand and get rid of ~90 LOC :) 
closes #3677
=> Refactor: StoreUpdater

examples/react/src/examples/Overview/index.tsx, examples/react/src/examples/Validation/index.tsx, examples/svelte/src/routes/examples/overview/+page.svelte, packages/react/src/components/StoreUpdater/index.tsx, packages/react/src/container/ReactFlow/index.tsx, packages/react/src/hooks/useGlobalKeyHandler.ts, packages/react/src/hooks/useReactFlow.ts, packages/react/src/index.ts, packages/react/src/types/component-props.ts, packages/react/src/types/instance.ts, packages/react/src/types/store.ts, packages/svelte/src/lib/container/SvelteFlow/SvelteFlow.svelte, packages/svelte/src/lib/container/SvelteFlow/types.ts, packages/svelte/src/lib/container/SvelteFlow/utils.ts, packages/svelte/src/lib/hooks/useSvelteFlow.ts, packages/svelte/src/lib/store/index.ts, packages/svelte/src/lib/store/initial-store.ts, packages/system/src/types/general.ts, packages/system/src/utils/graph.ts
=> Feat(deletions): add onBeforeDelete handler

packages/react/src/additional-components/Background/types.ts, packages/react/src/additional-components/Controls/types.ts, packages/react/src/additional-components/MiniMap/types.ts, packages/react/src/additional-components/NodeResizer/types.ts, packages/react/src/additional-components/NodeToolbar/types.ts, packages/react/src/components/Panel/index.tsx, packages/react/src/types/component-props.ts, packages/react/src/types/edges.ts, packages/svelte/src/lib/components/BaseEdge/types.ts, packages/svelte/src/lib/container/Panel/types.ts, packages/svelte/src/lib/container/SvelteFlow/types.ts, packages/svelte/src/lib/plugins/Background/types.ts, packages/svelte/src/lib/plugins/Controls/types.ts, packages/svelte/src/lib/plugins/Minimap/types.ts, packages/svelte/src/lib/plugins/NodeResizer/types.ts, packages/svelte/src/lib/plugins/NodeToolbar/types.ts, packages/svelte/src/lib/types/general.ts, packages/system/src/types/edges.ts, packages/system/src/types/handles.ts, packages/system/src/types/nodes.ts
=> Improve type docs

packages/core/src/hooks/useReactFlow.ts
Was working through an issue I was having and found this array/tuple sitting alone within an if statement. I imagine a return was accidentally missed here, so I thought I would add it.
Please let me know if this is the wrong branch or wrong format :)
=> Add Potentially Missed Return in useReactFlow getNodeRect

packages/react/CHANGELOG.md, packages/react/src/container/FlowRenderer/index.tsx, packages/svelte/CHANGELOG.md, packages/svelte/src/lib/container/Pane/Pane.svelte
=> Selection process is not interrupted by selectionKey being let go

packages/react/src/container/GraphView/index.tsx
=> type: remove repeated type

.changeset/nice-peaches-sit.md, .changeset/silent-years-explain.md, examples/vite-app/src/examples/Stress/index.tsx, examples/vite-app/src/examples/Subflow/index.tsx, examples/vite-app/src/examples/UpdatableEdge/index.tsx, packages/background/CHANGELOG.md, packages/background/package.json, packages/controls/CHANGELOG.md, packages/controls/package.json, packages/core/CHANGELOG.md, packages/core/package.json, packages/core/src/components/Edges/wrapEdge.tsx, packages/core/src/components/Nodes/wrapNode.tsx, packages/core/src/container/NodeRenderer/index.tsx, packages/core/src/store/utils.ts, packages/core/src/types/nodes.ts, packages/core/src/utils/changes.ts, packages/minimap/CHANGELOG.md, packages/minimap/package.json, packages/node-resizer/CHANGELOG.md, packages/node-resizer/package.json, packages/node-toolbar/CHANGELOG.md, packages/node-toolbar/package.json, packages/reactflow/CHANGELOG.md, packages/reactflow/package.json
* fix(nodes): re-measure/re-init nodes correctly closes #3886
* fix(edge-marker): use quotes for marker urls to support css vars closes #3915
=> React Flow 11.10.4

packages/system/src/xydrag/XYDrag.ts
=> fix node drag start & stop being fired when draggable=false

examples/react/src/examples/Basic/index.tsx, packages/system/src/xydrag/XYDrag.ts
=> Fire node drag events also when dragging selection

packages/react/src/components/NodeWrapper/index.tsx, packages/react/src/container/Pane/index.tsx, packages/svelte/src/lib/components/EdgeWrapper/EdgeWrapper.svelte, packages/svelte/src/lib/container/EdgeRenderer/EdgeRenderer.svelte, packages/svelte/src/lib/container/Pane/Pane.svelte, packages/system/src/styles/init.css
We need to check if the sensible default for nodes is cursor `pointer` or `default`
=> Draggable cursor fix

packages/react/src/components/EdgeWrapper/index.tsx, packages/react/src/components/NodeWrapper/index.tsx, packages/react/src/container/EdgeRenderer/index.tsx, packages/react/src/types/edges.ts
=> disableKeyboardA11y now correctly prevents escape key presses

packages/system/src/utils/edges/smoothstep-edge.ts
=> fixed smoothstep edge if center = 0

examples/react/src/examples/CustomNode/index.tsx, packages/react/CHANGELOG.md, packages/react/src/components/Handle/index.tsx, packages/react/src/container/ReactFlow/index.tsx, packages/react/src/types/component-props.ts, packages/react/src/types/general.ts
=> fix(react): ReactFlow comp ref type

packages/react/src/container/GraphView/index.tsx, packages/system/src/styles/init.css
Is it ok to add user-select: none to the whole viewport?
=> prevent selection of viewport

packages/svelte/CHANGELOG.md, packages/svelte/src/lib/components/Handle/Handle.svelte
connectionindicator class is now added if handle can be connected to based on handle types
=> Svelte Flow: connectionindicator class applied correctly

packages/react/src/components/Handle/index.tsx, packages/svelte/src/lib/components/Handle/Handle.svelte, packages/system/src/xyhandle/XYHandle.ts
added check to xyhandle pointermove if connection is cancelled
=> Connections can be correctly cancelled

packages/react/src/hooks/useKeyPress.ts, packages/svelte/src/lib/components/KeyHandler/KeyHandler.svelte
=> Fix context menu key up

packages/system/src/xypanzoom/XYPanZoom.ts, packages/system/src/xypanzoom/filter.ts
=> fixed double tapping on touch devices circumvents zoomOnDoubleClick

packages/svelte/src/lib/store/index.ts
I could be wrong about this. See the discussion in https://github.com/xyflow/xyflow/discussions/4179.
=> Do not reset nodes and edges — they are controlled by the user

examples/svelte/src/routes/examples/overview/+page.svelte, packages/svelte/src/lib/components/EdgeWrapper/EdgeWrapper.svelte, packages/svelte/src/lib/container/EdgeRenderer/EdgeRenderer.svelte, packages/svelte/src/lib/container/SvelteFlow/SvelteFlow.svelte
=> added edgemouseenter and edgemouseleave events

packages/svelte/src/lib/store/index.ts
I don't understand why this works.
closes #4327
=> Svelte: Fix deselection of edges

packages/svelte/src/lib/container/Panel/Panel.svelte
=> removed pointer events from panel when user selection is active

packages/system/src/xypanzoom/filter.ts
=> prevent zooming on mobile if zoomOnPinch is false

packages/system/src/xydrag/XYDrag.ts
=> abort drag when multiple touches are detected

examples/react/src/examples/DragNDrop/index.tsx, packages/react/CHANGELOG.md, packages/react/package.json, packages/svelte/CHANGELOG.md, packages/svelte/package.json, packages/system/package.json, packages/system/src/utils/dom.ts
=> React Flow 12.0.0-next.21 & Svelte Flow 0.1.6

packages/react/src/container/FlowRenderer/index.tsx, packages/react/src/container/Pane/index.tsx, packages/react/src/hooks/useGlobalKeyHandler.ts, packages/svelte/src/lib/container/Pane/Pane.svelte
=> Better selection usability

.changeset/nasty-shoes-promise.md, packages/react/src/container/Pane/index.tsx, packages/svelte/src/lib/container/Pane/Pane.svelte
=> fix(selection): handle pointer capture for selectionOnDrag

.changeset/blue-beers-report.md, packages/react/src/store/index.ts
=> fix nodeExtent causing jumping when dragging

.changeset/perfect-spiders-bathe.md, packages/react/src/container/Pane/index.tsx, packages/svelte/src/lib/container/Pane/Pane.svelte
=> only capture pointer after valid selection has started

packages/react/src/components/BatchProvider/useQueue.ts, packages/react/src/components/StoreUpdater/index.tsx
=> chore: fix typo

.changeset/empty-guests-yawn.md, packages/system/src/styles/init.css
=> refactor(edges): strengthen css selector for overflow visible

.changeset/mighty-nails-cover.md, examples/react/src/App/routes.ts, examples/react/src/examples/EasyConnect/CustomNode.tsx, examples/react/src/examples/MovingHandles/MovingHandleNode.tsx, examples/react/src/examples/MovingHandles/index.tsx, packages/react/src/components/Handle/index.tsx, packages/system/src/xyhandle/XYHandle.ts, packages/system/src/xyhandle/types.ts, packages/system/src/xyhandle/utils.ts
fixes #4027 
closes #4520 
related #3988
fixes #3983
=> Improve search algorithm for close handles

.changeset/modern-poems-joke.md, packages/react/src/types/store.ts
=> Fix edge type in store

.changeset/heavy-crews-invite.md, packages/react/src/container/Pane/index.tsx, packages/svelte/src/lib/container/Pane/Pane.svelte, packages/system/src/styles/init.css
=> Fix grab cursor

.changeset/rare-gorillas-repair.md, examples/svelte/src/routes/examples/intersections/Flow.svelte, examples/svelte/src/routes/examples/intersections/nodes-and-edges.ts, packages/svelte/src/lib/hooks/useSvelteFlow.ts
=> Fix intersections in Svelte Flow

.changeset/lovely-glasses-perform.md, packages/react/src/components/EdgeWrapper/EdgeUpdateAnchors.tsx, packages/react/src/components/EdgeWrapper/index.tsx, packages/system/src/xyhandle/XYHandle.ts, packages/system/src/xyhandle/utils.ts
=> Fix reconnect with loose connectionMode

.changeset/new-schools-watch.md, packages/react/src/hooks/useReactFlow.ts, packages/react/src/types/instance.ts, packages/svelte/src/lib/hooks/useSvelteFlow.ts
- Add `getHandleConnections` helper to `useReactFlow` & `useSvelteFlow`
=> feat(react,svelte): add `getHandleConnections` helper to `useReactFlow` & `useSvelteFlow`

.changeset/dull-bags-know.md, packages/react/src/hooks/useReactFlow.ts, packages/react/src/types/instance.ts, packages/svelte/src/lib/hooks/useSvelteFlow.ts, packages/svelte/src/lib/plugins/NodeToolbar/NodeToolbar.svelte, packages/system/src/utils/graph.ts
=> Added getNodesBounds function to useReactFlow/useSvelteFlow

.changeset/rude-rockets-hope.md, .changeset/twenty-ads-breathe.md, examples/react/src/examples/Subflow/index.tsx, packages/react/src/components/NodeWrapper/index.tsx, packages/react/src/components/ReactFlowProvider/index.tsx, packages/react/src/container/ReactFlow/Wrapper.tsx, packages/react/src/container/ReactFlow/index.tsx, packages/react/src/store/index.ts, packages/react/src/store/initialState.ts, packages/svelte/src/lib/container/SvelteFlow/SvelteFlow.svelte, packages/svelte/src/lib/container/SvelteFlow/types.ts, packages/svelte/src/lib/store/index.ts, packages/svelte/src/lib/store/initial-store.ts, packages/svelte/src/lib/store/utils.ts, packages/system/src/utils/general.ts, packages/system/src/utils/graph.ts, packages/system/src/utils/store.ts
=> fix node extent

.changeset/brave-worms-study.md, examples/react/src/examples/UseNodesData/index.tsx, examples/svelte/src/routes/examples/usenodesdata/+page.svelte, packages/svelte/src/lib/hooks/useNodesData.ts
=> fix useNodesData returning undefined in svelte flow

.changeset/new-rocks-mate.md, packages/system/src/xydrag/utils.ts
=> Fix rare crash: remove non-null assertion while dragging

.changeset/clever-keys-pay.md, packages/react/src/hooks/useKeyPress.ts
=> Enhance useKeyPress top also support '+'

.changeset/cuddly-mails-kneel.md, packages/react/src/types/nodes.ts, packages/svelte/src/lib/types/nodes.ts
=> refactor(types): add group node to BuiltInNode type

.changeset/many-emus-begin.md, packages/react/src/hooks/useReactFlow.ts, packages/svelte/src/lib/hooks/useSvelteFlow.ts
=> Fix intersection for various node origins

.changeset/old-bikes-wave.md, examples/react/src/examples/UseNodeConnections/MultiHandleNode.tsx, examples/react/src/examples/UseNodeConnections/index.tsx, packages/system/src/utils/store.ts
=> Fix useNodeConnection

packages/react/package.json
allow read `package.json`, fixes
=> feat(react): add `"./package.json": "./package.json",` in exports field of `package.json`

.changeset/few-rice-drive.md, packages/svelte/package.json
similar to https://github.com/xyflow/xyflow/pull/5006 to read `version` field in `package.json` https://github.com/xyflow/web/blob/a54c1c8253e2c00ca23194872c6f96230d201dcd/sites/svelteflow.dev/next.config.mjs#L4-L7
=> add `"./package.json": "./package.json",` in `exports` field in `package.json`

.changeset/late-pugs-thank.md, packages/react/src/components/Handle/index.tsx
=> fix(click-connections): handle isConnectableStart correctly 

.changeset/old-moles-push.md, packages/react/src/components/SelectionListener/index.tsx, packages/react/src/container/ReactFlow/index.tsx, packages/react/src/hooks/useOnSelectionChange.ts, packages/react/src/types/component-props.ts, packages/react/src/types/general.ts, packages/react/src/types/store.ts
=> fix(OnSelectionChangeFunc): pass node and edge type generics 

.changeset/twenty-sloths-reflect.md, packages/react/src/additional-components/MiniMap/MiniMap.tsx, packages/svelte/src/lib/plugins/Minimap/Minimap.svelte
=> refactor(minimap): do not show hidden nodes 

.changeset/thirty-terms-grow.md, packages/react/src/components/BatchProvider/index.tsx
=> Fix fitView when returning onNodesChanges early

.changeset/happy-pots-sell.md, packages/react/src/additional-components/NodeResizer/NodeResizeControl.tsx, packages/system/src/xyresizer/XYResizer.ts
=> refactor(node-resizer): pass latest dimensions to onEnd handler / resize change event

.changeset/curly-kangaroos-clap.md, packages/react/src/types/component-props.ts
Removed all mentions of "edges" in the docstring of onNodesChange and replaced them with mentions of "nodes"
=> Fixed onNodesChange docstring in component-props.ts

.changeset/nine-glasses-raise.md, packages/react/src/components/Attribution/index.tsx, packages/react/src/container/EdgeRenderer/MarkerDefinitions.tsx
=> chore(marker): add aria-hidden true

.changeset/giant-pets-draw.md, packages/react/src/hooks/useNodesInitialized.ts, packages/react/src/store/index.ts, packages/react/src/store/initialState.ts, packages/react/src/types/store.ts, packages/system/src/utils/store.ts
=> Use nodesInitialized from adoptUserNodes

.changeset/hip-fireants-change.md, packages/svelte/src/lib/store/index.ts
=> Remove setting nodesInitialized multiple times

.changeset/blue-gorillas-help.md, .changeset/funny-mayflies-grin.md, .changeset/sour-flowers-love.md, .changeset/twenty-panthers-report.md, examples/astro-xyflow/package.json, examples/astro-xyflow/src/components/SvelteFlowExample/index.svelte, examples/astro-xyflow/src/components/SvelteFlowInitialExample/index.svelte, examples/astro-xyflow/src/pages/index.astro, packages/svelte/src/lib/actions/portal/index.ts, packages/svelte/src/lib/actions/portal/portal.svelte.ts, packages/svelte/src/lib/actions/portal/utils.svelte.ts, packages/svelte/src/lib/components/EdgeLabel/EdgeLabel.svelte, packages/svelte/src/lib/components/EdgeWrapper/EdgeWrapper.svelte, packages/svelte/src/lib/components/Handle/Handle.svelte, packages/svelte/src/lib/components/NodeWrapper/NodeWrapper.svelte, packages/svelte/src/lib/components/ViewportPortal/ViewportPortal.svelte, packages/svelte/src/lib/plugins/NodeToolbar/NodeToolbar.svelte, packages/svelte/src/lib/store/initial-store.svelte.ts, pnpm-lock.yaml
=> Fix SSR and portals in Svelte Flow & update Astro Example

CONTRIBUTING.md
Added only one introductory sentence compared to the original in Notion.
=> docs(CONTRIBUTING): add changeset style guide

.changeset/plenty-garlics-fail.md, examples/svelte/src/routes/examples/usenodesdata/ResultNode.svelte, packages/svelte/src/lib/hooks/useNodeConnections.svelte.ts
=> Fix useNodeConnections callbacks firing only when returned signal is used

.changeset/friendly-pears-float.md, packages/react/src/components/Panel/index.tsx, packages/svelte/src/lib/container/Panel/Panel.svelte, packages/system/src/styles/init.css
=> refactor(panel): simplify / fix panel pointer events 

.changeset/twelve-llamas-sort.md, examples/react/src/examples/CustomConnectionLine/index.tsx, examples/svelte/src/routes/examples/custom-connection-line/+page.svelte, packages/react/src/components/EdgeWrapper/EdgeUpdateAnchors.tsx, packages/react/src/components/Handle/index.tsx, packages/react/src/components/StoreUpdater/index.tsx, packages/react/src/container/ReactFlow/index.tsx, packages/react/src/store/initialState.ts, packages/react/src/types/component-props.ts, packages/react/src/types/store.ts, packages/svelte/src/lib/components/EdgeReconnectAnchor/EdgeReconnectAnchor.svelte, packages/svelte/src/lib/components/EdgeReconnectAnchor/types.ts, packages/svelte/src/lib/components/Handle/Handle.svelte, packages/svelte/src/lib/container/SvelteFlow/Wrapper.svelte, packages/svelte/src/lib/container/SvelteFlow/types.ts, packages/svelte/src/lib/store/initial-store.svelte.ts, packages/system/src/xyhandle/XYHandle.ts, packages/system/src/xyhandle/types.ts
=> Add connectionDragThreshold

.changeset/forty-dryers-cry.md, .changeset/purple-donuts-fail.md, examples/react/src/App/routes.ts, examples/react/src/examples/DefaultEdgeOverwrite/index.tsx, examples/react/src/examples/DefaultNodeOverwrite/index.tsx, packages/react/src/components/EdgeWrapper/index.tsx, packages/react/src/components/NodeWrapper/index.tsx
Fixes #5383.
Tell me if I do anything wrong, I'd be happy to fix them :). I didn't touch the svelte package because I have almost zero knowledge of it.
=> fix(react): respect custom default node/edge type when falling back from unknown type

.changeset/popular-apples-invent.md, packages/react/src/hooks/useReactFlow.ts, packages/react/src/types/instance.ts, packages/svelte/src/lib/hooks/useSvelteFlow.svelte.ts
=> `getNodeIntersections`: calculate overlapping area correctly 

.changeset/perfect-poems-tap.md, packages/system/src/xydrag/XYDrag.ts, packages/system/src/xydrag/utils.ts
=> chore(multiselect): snap selection instead of single nodes 

.changeset/gentle-chefs-travel.md, packages/react/src/hooks/useReactFlow.ts, packages/svelte/src/lib/hooks/useSvelteFlow.svelte.ts
=> Fix is intersecting

.changeset/chilled-tigers-compare.md, packages/react/src/container/ZoomPane/index.tsx, packages/svelte/src/lib/actions/zoom/index.ts, packages/svelte/src/lib/container/Zoom/Zoom.svelte, packages/system/src/types/panzoom.ts, packages/system/src/xyhandle/XYHandle.ts, packages/system/src/xypanzoom/XYPanZoom.ts, packages/system/src/xypanzoom/filter.ts
=> Fix connection pinch

.changeset/lucky-shoes-design.md, examples/svelte/src/routes/examples/node-resizer/+page.svelte, examples/svelte/src/routes/examples/node-resizer/BottomRightResizer.svelte, packages/svelte/src/lib/plugins/NodeResizer/ResizeControl.svelte, packages/svelte/src/lib/plugins/NodeResizer/types.ts
=> Svelte Flow: resizeDirection

.changeset/lazy-yaks-occur.md, examples/react/src/examples/Stress/index.tsx, packages/react/src/components/EdgeWrapper/index.tsx, packages/react/src/components/NodeWrapper/index.tsx, packages/react/src/container/EdgeRenderer/index.tsx, packages/react/src/container/NodeRenderer/index.tsx
=> Memoize wrappers
