src/components/Handle/index.tsx

* id is used in an example
* isValidConnection has to take the connection argument to validate

Improve Handle Properties typings

---

README.md
example/src/Interaction/index.js
src/container/GraphView/index.tsx
src/container/ReactFlow/index.tsx

First off - thanks for creating and maintaining this library. I have found it to be extremely powerful, especially how the internal state and actions are exposed.
I have a use case where I need to know when the zoom pane has been clicked. This PR would allow developers to optionally hook into this event.
Feel free to let me know if there are other ways you think this can/should be accomplished.

feat(props): add onZoomPaneClick

---

cypress/integration/flow/interaction.spec.js
example/src/Interaction/index.js
src/components/Edges/wrapEdge.tsx
src/components/Nodes/wrapNode.tsx

It would be useful to have the `onElementClick` event run, even if elements are not selectable or draggable.

Always run `onElementClick` if provided, regardless of `isSelectable` or `isDraggable`

---

src/additional-components/MiniMap/MiniMapNode.tsx
src/additional-components/MiniMap/index.tsx
src/index.ts

Hi,
We exposed `getConnectedEdge` as it met exactly our needs but it wasn't exported, even though it is very easy to use.
We also added a `nodeClassName?: StringFunc | string` prop to the `MiniMap` component to pass a custom class name to the nodes, with the possibility to customize it for each individual node.
In our case we needed this to display each node in the same color in the pane and in the minimap directly from the SCSS.
Before this change we could only do this through JS which forced us to duplicate the color palette in SCSS and JS.
I have to warn you that I was not able to run all tests locally, as it first complained about missing a very specific version of eslint (which I had to install manually), then that it could not find React in the compiled files, even though it was …

Expose getConnectedEdge + Set className of minimap node

---

src/additional-components/Controls/style.css

Set border-box explicitly so upstream frameworks don't upset the layout.

fix: Set border-box explicitly on Controls

---

src/container/EdgeRenderer/index.tsx

I've had trouble tracking down erroneously configured edges (e.g. incorrectly configured source handle). 
This small change just outputs the edge id in the warning to assist in tracking down the issue, as getting just:
> ⚠️ couldn't create edge for source handle id: null
doesn't really help in tracking down which edge I need to fix.

chore(edge): Output edge id with source/target warnings

---

src/types/index.ts

This is very minor, but very convinient.
Not breaking (due to default type set to any `T=any`).
Now this is possible:
```tsx
const CustomNodeComponent = (props: NodeProps<{label:JSX.Element}>) => {
return (
<div>{props.data.label}</div>    // inferred currectly
);
}
```

[Types]: Add type inference for data property

---

src/additional-components/Background/index.tsx
src/additional-components/Background/utils.ts
src/additional-components/Background/utils.tsx

I had a go at changing the rendering of the svg background to use svg patterns instead of css tiling, from my testing it looks like it resolves issue #577.
I haven't looked at the performance implications of this so would be good to get your opinion. Also would be good to confirm if you no longer see the missing dots/lines issue.

Use svg pattern for background instead of css tiling

---

src/additional-components/MiniMap/MiniMapNode.tsx
src/additional-components/MiniMap/index.tsx
src/style.css

Borders from the nodes on the minimap would clip terribly on non-Chrome browsers. This was caused by them having the css `shape-rendering: crispedges;`. Changing this to `shape-rendering: geometricPrecision;` fixes the issue on non-Chrome browsers but breaks it on Chrome.
Example:
Chrome:
Firfox:
Removing the CSS and instead moving the `shapeRendering` directly into the SVG-element allows us to first check if a user is using Chrome or not. If a user is using Chrome we still use `crispEdges`, else we can use `geometricPrecision`.

Fixed minimap node borders on Safari, Chrome, etc

---

src/components/Edges/wrapEdge.tsx
src/style.css

The first EdgeAnchor is disturbed by the EdgeComponent (the line). To demonstrate this, you can see on the screenshot, if we fill the line path and the circle of the edge anchor, the red one cannot be dragged because the line path goes under it.
On the `wrapEdge` file, I just change the order of the svg elements. Like this anchors are always on the top.

fix(edge): change order of the first EdgeAnchor disturbed by the EdgeComponent

---

example/src/DragNDrop/Sidebar.tsx
example/src/DragNDrop/dnd.css

Otherwise the styles diverge and nodes look different on the sidebar and the canvas.
After the fix:

Examples - Drag and drop - Using the theme styles for the sidebar nodes

---

.gitignore
src/components/Edges/SmoothStepEdge.tsx

fixed smoothStepEdge behaviour for sourceX > targetX case

fixed smoothStepEdge behaviour for sourceX > targetX case

---

package.json

The version of the peer dependency `react-dom` should be `16 || 17` instead of `17 || 17`. This bug prevents projects using React Dom 16 from installing version `9.6.3`.
Right version (9.6.0): https://github.com/wbkd/react-flow/commit/f835f85e65545ac87eb5bd2247a4ea1ebaee85ec
Changed to 17 only (9.6.1 ?): https://github.com/wbkd/react-flow/commit/290ba99f7048c04687255e4ff2cb175675d5432f
Got typo when you changed it back (9.6.3): https://github.com/wbkd/react-flow/commit/8c4ae0cb5deda608b990df7cf9c900baac3245e0
This haven't been tested yet, but it should work 😄

BUG FIX: should support react-dom 16 and 17

---

src/components/ConnectionLine/index.tsx
src/types/index.ts

Include Node and Handle in props passed to custom connection lines for advanced usage.
I created advanced label handles for a project and realized that the center of handle source tuple was not sufficient for my use case, rather than modify this behavior I could easily adjust the source position if I had access to the handle which the default connection line already finds. this change passes that power onto custom implementations. This allows me to add a `sourceX+(sourceHandle.width/2 - 5)` offset for `Position.Right` source handles. Power than I needed to satisfy application requirements by our design team.

Extend Connection Lines

---

src/components/Edges/wrapEdge.tsx
src/container/EdgeRenderer/index.tsx

I am using the drag-and-drop function and Edge Update function by applying it to my project, but EdgeUpdate sometimes does not work well.
When I checked, it was not included in the dependencies of the useCallback functions that use onEdgeUpdate.
The onEdgeUpdate function code I used is   
```typescript
const [elements, setElements] = useState<Elements>(initialElements);
const onEdgeUpdate = (oldEdge: Edge, newConnection: Connection) =>
setElements(updateEdge(oldEdge, newConnection, elements));
```
I think it's better to use the onEdgeUpdate Code from Example, but I hope this code works as well.
Below is a picture of edgeUpdate not working

Fix when it disappears when connecting an edge to update to a new node

---

src/store/reducer.ts

This is the intended logic. Without it triggering this action with a node id will always move selected nodes, which is not desirable if we want to move just an unselected node.
The bug doesn't show up in current examples because at the moment either one selected node is moved or all the selected nodes are moved. TBH this should probably be changed to accept `ids` instead to handle the two cases instead of this tight coupling between the group selection code and this action.

Fix bug in updateNodePosDiff action

---

example/src/UseZoomPanHelper/index.tsx
src/hooks/useZoomPanHelper.ts
src/types/index.ts

Smooth transitions were a highly requested feature for react-flow that could be implemented using external libraries like popmotion or tween.js, but this approach is a bit messy since you need to use the reactFlowRef and change its internal viewport directly.
There are some [built-in functions](https://github.com/d3/d3-zoom#zoom_transform) in D3.js that can help with smooth transitions without using any external libraries.  
I've refactored the `useZoomPanHelper` hook functions to use d3 transitions and added the corresponding examples to `/examples/UseZoomPanHelper` directory.
I've also added an optional duration argument to the `zoomIn, zoomOut, zoomTo, transform, fitView, setCenter` and `fitBounds` functions to help the user to change the duration of d3 transitions.
By default, all the …

Smooth transitions for useZoomPanHelper using built-in d3 functions

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/config.yml

1. Add  `bug_report.md`  to enable Github's new issue template form 
- https://youtu.be/qQE1BUkf2-s?t=23
2. Add `config.yml` file to direct user's to the right place if they are looking to create an issue or  ask question
- encourage's bug reporter's to put more care into their bug report before submission
- this may help `react-flow`'s maintainer's receive more detailed & higher quality bug report's (_benefits user's / readers as well_)
- prevents bug reporter from submitting a bug IF they do not fill in the required fields specified in the `bug_report.yml` file
- adds helpful tips for user's during the process of creating a bug/issue report
- https://github.com/cliffordfajardo/TEST-react-flow-gh-template/issues/new/choose

add github issue templates

---

src/container/EdgeRenderer/index.tsx

While implementing react-flow in our application I wanted to move the selectedNode to the center of the screen. This makes sure the user can find it even on larger trees. 
To achieve that I added a transition to the two places the translation is applied:
```css
.react-flow__nodes, .react-flow__edges *: {
transition: transform 500ms ease-in-out,
}
```
This works fine in Chrome,. When testing in Firefox the transition did not work however. This seemed to be related to the transfrom being applied as an attribute by react-flow. Attributes are only targeted by the [SVG2](https://www.w3.org/TR/SVG2/) spec which has already been partially implemented in Chrome, but not in Firefox. 
To fix this I tested moving the transform into a style tag like it is done for the nodes. …

Fix Firefox not being transitioned

---

src/container/ReactFlow/index.tsx

Solves problem: cannot pass ref
Error text:  "Property 'ref' does not exist on type 'IntrinsicAttributes & ReactFlowProps & { children?: ReactNode; }'."
Explanation: implicitly type React.ForwardRefExoticComponent<ReactFlowProps & React.RefAttributes<ReactFlowRefType<ReactFlowRefType>>>

Removed wrong type

---

src/components/ConnectionLine/index.tsx
src/components/Edges/BezierEdge.tsx
src/components/Edges/SimpleBezierEdge.tsx
src/types/edges.ts

- I rewrote the Bezier function to make it more clear and different positions are handled uniformly.
- ~~I added the `sourceCurvature` and `targetCurvature` to address the connection line problem, where the destination is not known in advance when connecting.~~ Upon reflection I removed these two parameter: https://github.com/wbkd/react-flow/pull/1984#issuecomment-1072294366.
- I splitted `getBezierPath` and `getSimpleBezierPath` into two functions. As I understand, simple Bezier and a Bezier with curvature equals to `0` are two different shapes. Simple Bezier actually has control points at the center of the edge, while `curvature = 0` means the control points coincide with the start or end point. In the existing code, setting `curvature` to `0` and `0.000001` will create two totally …

refactor Bezier function

---

example/src/CustomNode/ColorSelectorNode.tsx
src/components/Edges/wrapEdge.tsx
src/components/Handle/handler.ts
src/components/Handle/index.tsx

This PR fixed an issue that when setting `onMuseDown` props on `<Handle/>` where in  custom a node, the all connect event is invalid.Because the out props `onMuseDown` is pass to `<div/>` by `...rest` . and It is overwrite  the inner onMouseDownHandler.

fix: fixed an issue where Handle component onMouseDown event could not be bind

---

src/hooks/useReactFlow.ts

This fixes #2147.
I fixed by adding a check for empty change arrays. If the change array is empty, I create a new change array that removes all edges/nodes by id.
Hacky, yes, but it doesn't change any public types. My original idea was to either:
1. Change the `reset` type to `{ items: Node<NodeData>[]; type: 'reset'; }`,
1. Change the `reset` type to `{ item: Node<NodeData> | undefined; type: 'reset'; }`, or
1. Add a new change type `{ newItems: Node<NodeData>[]; type: 'reset-all'; }`
However, all of those are a breaking change because it would change the public API of `on{Nodes,Edges}Change` and `{Node,Edge}Change`.
---
Also, when running `npm test`, I just get this:
```ps
PS C:\Users\micha\Git\react-flow> npm test
> react-flow-renderer@10.2.2 test
> BROWSER=none npm run dev:wait …
```

Fixed `setNodes` and `setEdges`

---

src/container/EdgeRenderer/index.tsx
src/container/FlowRenderer/index.tsx
src/container/GraphView/index.tsx
src/container/ReactFlow/index.tsx
src/style.css
src/types/component-props.ts

This implements solution 3 from #2158.
The connection line will now always have an exclusive `<svg>` element. This makes the implementation easier. I kept the old class name to stay backward compatible. The fix suggested in #810 will continue to work.

Added `connectionLineContainerStyle` property

---

README.md

I was getting errors without running starting the example but after I ran `npm run build`, I was able to start the example

added npm run build instruction

---

example/src/UseReactFlow/index.tsx
src/components/ConnectionLine/index.tsx
src/container/EdgeRenderer/utils.ts
src/container/NodeRenderer/index.tsx
src/hooks/useVisibleEdges.ts
src/index.ts
src/store/index.ts
src/store/utils.ts
src/types/nodes.ts
src/utils/index.ts

This PR introduces non-enumarable props for the internals: `handleBounds`, `z` and `isParent` so that they don't get exposed to user land.

refactor(internals): use non enumerable props

---

src/components/Handle/handler.ts

If two handles are next to each other or overlap it is possible for the
mouse-cursor to move from one handle to the other without a
mouse-move-event being fired where isHoveringHandle is false.
Thus, the valid and connecting css-classes were not removed from the
handle.
This commit fixes this.
To reproduce you can rearrange the nodes in the validation example like so:
And then drag a connection from the left node across the three overlapping handles.

fix(validation): Remove css-classes if mouse moves directly to different handle.

---

src/hooks/useDrag/index.ts
src/hooks/useDrag/utils.ts

I have an app where the user is able to toggle snapping and noticed some potentially undesirable behaviour. With the current implementation snapping is relative to the start position of the node. I think it makes more sense to snap relative to the centre point of the diagram so when snapping is enabled nodes can be neatly aligned relative to each other.
A quick example, let's say a diagram has a `gridSize=[10, 10]`. With snapping disabled `snapToGrid={false}` the user moves a node to `[7, 7]`. Then the user enables snapping `snapToGrid={true}`. With the current implementation when the user moves the same node it will snap to `[17, 17]`, `[27, 27]` and so on. I think it makes more sense the node would snap to `[10, 10]`, `[20, 20]` or `[30, 30]`.
My proposed code changes fix this though …

Snap node to grid relative to 0,0 instead start position of node

---

src/hooks/useKeyPress.ts

This PR fixes a problem where keystrokes are not being registered when originating from shadow DOM inputs. Current react-flow implementation attaches a global event listener for `keydown` event and calls `preventDefault()` on it if the following 2 conditions are met:
1. The key name is registered (using props like `deleteKeyCode`, `multiSelectionKeyCode` etc.)
2. **`isInputDOMNode` returns true** 
[This article ](https://tinytip.co/tips/js-event-composed-path/)explains why the current implementation of `isInputDOMNode` doesn't work as well as shows a solution which is used in this PR
Reproducible demo sandbox: https://codesandbox.io/s/react-flow-with-shadow-dom-lymfwm?file=/index.js

Use event.composedPath for getting event target (keydown shadow DOM fix)

---

examples/vite-app/index.html
examples/vite-app/src/App/index.tsx

- Example routes have names so they are getting shown better in dropdown
- The title of the examples has been changed to "React Flow Examples - [Example Name]", so that if a development needs to be tested in two different examples at the same time, our tabs will be sufficiently organised.

chore(examples): example page title corrected

---

examples/vite-app/src/examples/ControlledUncontrolled/index.tsx
examples/vite-app/src/examples/DefaultNodes/index.tsx
examples/vite-app/src/examples/EdgeRouting/index.tsx
examples/vite-app/src/examples/Provider/Sidebar.tsx
examples/vite-app/src/examples/UseKeyPress/index.tsx

Extra `import React from 'react'`s removed from examples. Some imports remained in the files after switching to Vite, despite the fact that Vite will handle it automatically and there is no need to import them for our JSX.

fix(examples): extra react imports removed

---

packages/reactflow/package.json

According to the webpack docs about tree shaking, css files should be considered as side effects: https://webpack.js.org/guides/tree-shaking/#:~:text=**/*.css.-,Tip,-Note%20that%20any
This should fix #2477.

Add css files as sideEffects

---

.changeset/few-donkeys-eat.md
examples/vite-app/src/App/index.tsx
examples/vite-app/src/examples/EdgeRenderer/CustomEdge.tsx
examples/vite-app/src/examples/EdgeRenderer/CustomEdge2.tsx
examples/vite-app/src/examples/EdgeRenderer/index.tsx
packages/core/package.json
packages/core/src/components/EdgeLabelRenderer/index.tsx
packages/core/src/container/GraphView/index.tsx
packages/core/src/index.ts
packages/core/src/styles/init.css
pnpm-lock.yaml

The edges are SVG based. It was always a bit tricky to add more advanced edge labels (we had to use foreignObject, which is not nice). The new `EdgeLabelRenderer` component is a portal to div that can be used to render to labels like this:
```js
// this is part of a custom edge
<EdgeLabelRenderer>
<div
style={{
position: 'absolute',
transform: `translate(-50%, -50%) translate(${labelX}px,${labelY}px)`,
background: '#ffcc00',
padding: 10,
}}
>
{data.text}
</div>
</EdgeLabelRenderer>
```
closes #2494 closes #1906 #1464 #425

Feat: Add div based renderer for edge labels

---

.changeset/silly-taxis-drop.md
packages/core/src/store/utils.ts

Instead of only elevating when `zIndex` is unset

Always elevate 1000 in `zIndex` when node is selected

---

packages/core/src/container/ReactFlow/Wrapper.tsx

Previously, Wrapper used try..catch around a call to useStoreApi to check whether there was an available StoreContext, instead of simply using useContext and checking the value. This leads to poor developer experience when using the devtools feature "pause on caught exceptions" as it causes the devtools to break on every render of a Wrapper that is not within a StoreContext provider. The catch is also universal, meaning that it could catch a completely unrelated error and happily keep going instead of crashing which is undesirable.
This commit changes this try..catch into a simple call to useContext to check if a StoreContext is available.

ref: stop using try..catch as control flow in Wrapper

---

.changeset/neat-fishes-burn.md
.changeset/perfect-spiders-own.md
.changeset/silver-dots-try.md
.changeset/six-dolls-search.md
examples/vite-app/src/examples/NodeToolbar/SelectedNodesToolbar.tsx
examples/vite-app/src/examples/NodeToolbar/index.tsx
examples/vite-app/src/examples/Subflow/index.tsx
packages/core/src/container/ReactFlow/Wrapper.tsx
packages/core/src/hooks/useDrag/index.ts
packages/core/src/hooks/useDrag/utils.ts
packages/core/src/index.ts
packages/core/src/store/index.ts
packages/core/src/store/utils.ts
packages/core/src/utils/graph.ts
packages/core/src/utils/index.ts
packages/minimap/src/MiniMap.tsx
packages/node-toolbar/src/NodeToolbar.tsx
packages/node-toolbar/src/types.ts

* fix(subflow-node-origin): use node origin in node position calculation
* feat(node-toolbar): allow multiple nodeIds as property to enable multi node toolbar
* refactor(wrapper): don't use try catch

Next release

---

packages/core/src/components/Handle/handler.ts
packages/minimap/CHANGELOG.md
packages/reactflow/CHANGELOG.md

(in my opinion) A node shouldn't connect to itself on the same handle, and it becomes more obvious when one is trying to perform "click and connect" in the "loose" mode.
It could also be written as `!(elementBelowNodeId === nodeId && elementBelowHandleId === handleId)` depending preference, either way makes sense to me.

Invalidate a Node trying to connect itself with the same handle

---

.changeset/gorgeous-trees-double.md
examples/vite-app/src/examples/Basic/index.tsx
packages/core/src/components/StoreUpdater/index.tsx
packages/core/src/container/ReactFlow/index.tsx
packages/core/src/store/index.ts
packages/core/src/store/initialState.ts
packages/core/src/store/utils.ts
packages/core/src/types/component-props.ts
packages/core/src/types/general.ts

This pull request adds a new boolean prop `elevateNodesOnSelect` which can be used to disable the automatic elevation (zIndex + 1000) of nodes when they are selected.
closes #2625

feat(nodes): add prop to disable automatic elevation of nodes on select

---

packages/core/src/container/EdgeRenderer/index.tsx

Fixes #2630 by concatenating both handle types instead of only looking at targets if any exist. The initial behavior does not change, as targets get chosen preferentially if no handle id is given. This applies only to `ConnectionType.Loose`

Check both handle types in EdgeRenderer if ConnectionType is Loose

---

.changeset/dry-mice-explode.md
examples/vite-app/src/examples/Subflow/index.tsx
examples/vite-app/src/examples/Switch/index.tsx
packages/core/src/components/Handle/handler.ts
packages/core/src/components/Handle/index.tsx
packages/core/src/components/Handle/utils.ts
packages/core/src/components/StoreUpdater/index.tsx
packages/core/src/container/ReactFlow/index.tsx
packages/core/src/hooks/useDrag/index.ts
packages/core/src/store/index.ts
packages/core/src/store/initialState.ts
packages/core/src/types/component-props.ts
packages/core/src/types/general.ts
packages/core/src/utils/graph.ts
packages/core/src/utils/index.ts

When the user drags a node, selection or connection line to the corner of the pane the pane auto pans to that direction. 
Prop name ideas: `autoPanOnNodeDrag` & `autoPanOnConnect`
https://user-images.githubusercontent.com/2857535/213303284-65c9b1ad-87f0-40b9-8774-9dd2a0cb6186.mov
This PR also adds a new prop `connectionRadius` - this makes it possible to adjust the radius around a handle where you can connect an edge. This PR makes it easier to connect nodes because you don't need to drop the connection line above a handle but only close to it.
https://user-images.githubusercontent.com/2857535/213474804-763ba9c7-27e6-415f-bcd5-4a06f3f65fd9.mov

Auto pan for nodes, selection and connection line and connectionRadius

---

.changeset/pretty-spoons-punch.md
examples/vite-app/src/examples/NodeResizer/CustomResizer.tsx
examples/vite-app/src/examples/NodeResizer/CustomResizer2.tsx
examples/vite-app/src/examples/NodeResizer/CustomResizer3.tsx
examples/vite-app/src/examples/NodeResizer/NodeResizerNode.tsx
examples/vite-app/src/examples/NodeResizer/index.tsx
packages/node-resizer/package.json
packages/node-resizer/src/NodeResizer.tsx
packages/node-resizer/src/ResizeControl.tsx
packages/node-resizer/src/types.ts
packages/node-resizer/src/utils.ts
packages/node-toolbar/package.json

Two improvements are planned for the node resizer:
1. Add an ~`onBeforeResize`~  `shouldResize` handler that returns a boolean. This can be helpful to implement dimensions constraints that are based on other nodes for example.
```js
const shouldResize = (event, params) => {
return params.width < 100;
}
```
2. Add a `direction` attribute to the passed params in the event handlers. This is helpful if your calculations are different based on the direction where a resize movement comes from. Not sure how this could look like. Maybe [1, 0] for a movement to the right, [0, -1] to the top, [1, 1] to the bottom right and so forth?

Node-resizer: add shouldResize handler

---

packages/core/src/types/nodes.ts

I have added custom Node Types in my codebase and it could be great if I could set the type property of the Node type to an Enum or string literal. In order to support that, I have added another Generic to the Node type and then set the type property to exactly that generic type. Note that, the default of that generic type is the same as the current type is, so this change should be fully backwards compatible.
Also when making this change, I was wondering why type can be undefined?

Add generic support for the type property on the Node type

---

.changeset/sour-impalas-admire.md
examples/vite-app/src/examples/Validation/validation.module.css
packages/core/src/components/Handle/handler.ts
packages/core/src/components/Handle/utils.ts

- fixes an issue for connection on iOS touch devices
- doesn't snap connection line when connection is not valid
- use "valid" and "connecting" class names for handles (we are also still using "react-flow__handle-connecting" and "react-flow__handle-valid" for backwards compatibility) thanks @bcakmakoglu

fix(ios): connection error + dont snap invalid connection lines

---

.changeset/green-files-act.md
examples/vite-app/src/App/index.tsx
examples/vite-app/src/examples/CustomMiniMapNode/index.tsx
packages/minimap/src/MiniMap.tsx
packages/minimap/src/MiniMapNode.tsx
packages/minimap/src/types.ts

**This is WIP because my local env is broken and I can't test anything 😅**
- add `nodeComponent` prop to `<MiniMap />` for user-defined minimap nodes.
- expose `MiniMapNodeProps`.
- add example flow to `vite-app/examples`.

[WIP] feat: add prop to render custom node inside minimap

---

packages/core/src/container/ZoomPane/index.tsx

This fixes Chrome warning about non-passive wheel event listener by explicitly setting passive to false (which suppresses the warning). Fixes #546, fixes #1688.
```
[Violation] Added non-passive event listener to a scroll-blocking 'wheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
```
To reproduce the issue, open https://reactflow.dev in latest Chrome version and check the console for warnings (it could be required to reload the page with console opened).

fix non-passive wheel event listener violation

---

examples/vite-app/src/examples/Backgrounds/index.tsx
packages/background/src/Background.tsx
packages/background/src/types.ts

This allows multiple background components by introducing `id` property for the `<Background/>` component, which is used to distinguish the svg patterns. Also adds `offset` property to allow alternating patterns (4th example on the screenshot). This is (hopefully) a cleaner alternative solution for #2940.

allow mutliple backgrounds, add offset prop

---

examples/vite-app/src/examples/InteractiveMinimap/index.tsx
packages/minimap/src/MiniMap.tsx
packages/minimap/src/types.ts

This adds `inversePan` and `zoomStep` optional properties to minimap allowing to inverse pan control (making it similar with how panning work in graph flow) and to control zoom speed (again, to make it more similar with flow zooming).

add minimap inverse pan and zoom step

---

README.md

Link to cypress examples was taking users to a 404 page.
This PR updates the link so users are taken to the correct path, `examples/vite-app/cypress/`, instead of the incorrect one, `examples/cypress`.

[fix] Update link to Cypress examples in README.md

---

README.md
packages/minimap/src/MiniMap.tsx
packages/minimap/src/types.ts
packages/reactflow/README.md

Sorry for not creating a discussion first, but this one is pretty trivial.
Due to the `5` hard-coded value here:
https://github.com/wbkd/react-flow/blob/993a778b80cc1e80a47983ed75407b579313a73c/packages/minimap/src/MiniMap.tsx#L70
— minimap mask has a ~5px border even when the viewport is perfectly aligned with the map and all the nodes are inside: 
This doesn't work for me, as I need the mask to show only when nodes are outside the view or the view aspect ratio differs from map's, eg:
https://github.com/wbkd/react-flow/assets/2056864/bd93c88d-98aa-4b1c-aa16-6ccb88cd7379
Setting the value to 1 resolved the issue (and doesn't seem to break anything), but I guess it was added for a reason, hence the added prop with the old default value.

Allow controlling offset scale of minimap

---

packages/core/src/hooks/useKeyPress.ts

When pressing incorrect keys (according to the given keys to watch), when letting go of all keys some keys will stay as they are still pressed, hence making the `isMatchingKey` faulty and not trigger.
See https://stackoverflow.com/questions/27380018/when-cmd-key-is-kept-pressed-keyup-is-not-triggered-for-any-other-key
When retrieving an up-event for Meta key, remove all pressed keys.

fix(key-press): mac issue keyup not triggered

---

.changeset/weak-geese-dream.md
packages/core/src/components/Nodes/utils.ts
packages/core/src/components/Nodes/wrapNode.tsx
packages/core/src/contants.ts

Two changes:
- `handleNodeClick` no-ops if the target node doesn't exist.
- A new error is reported:
```js
`Node with id "${id}" does not exist, it may have been removed. This can happen when a node is deleted before the "onNodeClick" handler is called. If this wasn't on purpose, please defer deleting this node until the "onNodeClick" handler is called by using "requestAnimationFrame" or "setTimeout".`
```
This can come up if a custom node has a delete button, for example, and the user _also_ has a `onNodeClick` handler set up on the `<ReactFlow>` component.

🐛  Fixes a bug where 'handleNodeClick' could runtime error if the node had already been removed.

---

examples/vite-app/src/examples/EasyConnect/utils.tsx
examples/vite-app/src/examples/FloatingEdges/utils.ts

Hello Team!
While reviewing the changes introduced in the recent commit for the `getNodeIntersection` function, I've identified a critical concern related to how the coordinates are being calculated for `x1` and `y1`. This miscalculation could lead to inaccuracies in the resultant intersection point.
**Issue:**
In the current implementation, `x1` and `y1` are calculated using the `targetNodePosition` coordinates plus `w` and `h` variables, which represent half of the `intersectionNode`'s dimensions. This calculation assumes that the dimensions of `targetNode` and `intersectionNode` are the same, which might not always be the case. Adding `w` and `h` from the `intersectionNode` to the `targetNode`'s position offsets the target's actual center point, likely leading to an incorrect …

fix: calculation of target node center in examples

---

packages/svelte/src/lib/components/EdgeWrapper/EdgeWrapper.svelte

fix(svelte) undefined edge classes do not append "undefined" as class

---

.changeset/curly-points-travel.md
packages/core/src/components/NodesSelection/index.tsx
packages/core/src/hooks/useDrag/index.ts
packages/core/src/hooks/useViewportHelper.ts
packages/core/src/index.ts
packages/core/src/store/utils.ts
packages/core/src/utils/graph.ts
packages/minimap/src/MiniMap.tsx
packages/node-toolbar/src/NodeToolbar.tsx

deprecations/renamings:
* `useReactFlow.project` => `useReactFlow.screenToFlowPosition` (changes: no need to subtract react flow bounds anymore)
* `getRectOfNodes` => `getNodesBounds` (changes: none)
* `getTransformForBounds` => `getViewportForBounds` (changes: returns `{ x: number, y: number, zoom: number }` instead of `[number, number, number]`)
--
new functions:
* added `useReactFlow.flowToScreenPosition`

chore(utils): add renamed functions and deprecations closes #3528

---

packages/react/package.json
packages/react/src/additional-components/MiniMap/MiniMapNodes.tsx
packages/react/src/container/NodeRenderer/index.tsx
packages/react/src/hooks/useVisibleNodes.ts
packages/react/src/store/index.ts
packages/react/src/store/initialState.ts
packages/svelte/src/lib/store/initial-store.ts
packages/svelte/src/lib/store/utils.ts
packages/system/src/types/nodes.ts
packages/system/src/utils/store.ts
pnpm-lock.yaml

This PR ensures that when you’re dragging a node around the screen (or selecting it, or updating it in any other way), `NodeRenderer` (and `MiniMapNodes`) don’t rerender.
This prevents us from re-running [this loop](https://github.com/xyflow/xyflow/blob/8fe8f73ed3d7fc2a14b2ecbefffb1b988b2edaf8/packages/react/src/container/NodeRenderer/index.tsx#L78-L149) N times (N being the number of nodes) on every store update. With 500 nodes, it gets surprisingly expensive (20-40 ms with CPU throttling)!
(You can review this PR commit-by-commit.)
To make this possible, I had to make two significant design changes (both in 24390162e08867a7c68c309a0ebcd52dafd6d425).
**First,** I had to split the `Node` term into two: `InternalNode` and `UserProvidedNode`.
- `UserProvidedNode` means a node object that …

[Perf: Selection, Dragging] Don’t rerender NodeRenderer and MiniMapNodes unless necessary

---

packages/react/src/store/initialState.ts

This PR sets `nodeDragThreshold` to 1. This removes an expensive state and React update that would otherwise happen on `mouseup`.
Currently, whenever you select a node, XYFlow triggers two state updates:
This PR simply removes the second one.
With this PR, node selection gets 1.6× cheaper.
(To verify, try changing selection while running a recording in Chrome DevTools → Performance – and compare the total JS costs between `next` and this branch.)
If you look at this interaction really closely, you’ll notice we do a store update with `dragging: false` despite never setting `dragging: true`. Generally, this should be a no-op update (the node goes from not dragging to not dragging), but in the current codebase, it’s not: the update still triggers a React rerender.
This is an undesirable side …

[Perf: Selection] Set `nodeDragThreshold` to 1

---

examples/react/src/examples/Stress/index.tsx
examples/react/src/examples/Stress/performanceUtils.ts

This PR adds additional performance scenarios to the stress test:
and introduces a system for recording and [visualizing](https://observablehq.com/@iamakulov/long-frame-visualizer) them:
This PR adds four new buttons into the stress test, designed to test the most critical interactions:
- “select node”
- “drag within viewport”
- “drag outside of viewport”
- ”re-mount”
Unlike the existing buttons (“change pos” and etc.) which just change the React Flow state, “Select node”, ”Drag within the viewport” and “Drag outside of the viewport” actually emulate user interactions – by creating and dispatching fake mouse events:
```js
const node = document.querySelector(...);
node.dispatchEvent(new MouseEvent("mousedown", ...));
node.dispatchEvent(new MouseEvent("mousemove", ...)); …
```

[Perf] Add performance tests for selecting, dragging, and remounting

---

packages/react/src/components/Edges/BaseEdge.tsx
packages/react/src/components/Edges/EdgeText.tsx
packages/react/src/types/edges.ts

This PR add support for className in baseEdge, for those who wants to use tailwindcss and other css processors. In the actual scenario, it's necessary to create a **path** and send the edge Path to them to style the edge. It's possible to style with the **style property** too. But, not CSS. 
Other changes: 
Related to the EdgeLabelText.
The actual implementation of the EdgeLabelText is using an approach that observes the label changes, it's more "tracking perfect" to get the changes based on the reference itself, removing a re-render caused  by the useEffect.

fix(edges): add suport for className in baseEdge and remove unecessary render

---

LICENSE
packages/react/src/types/changes.ts
packages/react/src/types/general.ts
packages/react/src/utils/changes.ts

This PR is my take on a discussion regarding the same problem that can be found here:
- https://github.com/xyflow/xyflow/pull/2923
- https://github.com/xyflow/xyflow/issues/3030
I believe I improved the Lib's Typesafety without adding any breaking changes to it...
Let me know what you think 🙂 🚀 
Cheers! Thanks for the amazing lib 🙏🏻 
On some functions and type definitions related to Change Events,
the generics for the types Node and Edge were being lost.
This commit fixes those:
- Functions
- applyNodeChanges
- applyEdgeChanges
- Types
- NodeChange
- EdgeChange
- OnNodesChange
- OnEdgesChange

fix: typesafety of Node and Edge changes

---

packages/svelte/CHANGELOG.md
packages/svelte/src/lib/hooks/useSvelteFlow.ts

I think it is better to keep everything simple: not support `getEdges(id)` just `getEdges([id])`

add getNode, getNodes, getEdge, getEdges

---

packages/svelte/src/lib/container/SvelteFlow/SvelteFlow.svelte

If you setup on:panecontextmenu event handler on the SvelteFlow component no events are received since it was never wired up.
- Fixes right click feature on the pane

Svelte Flow: on:panecontextmenu is not propagated to top level component

---

packages/react/src/additional-components/MiniMap/MiniMap.tsx
packages/react/src/additional-components/MiniMap/types.ts
packages/svelte/src/lib/plugins/Minimap/Minimap.svelte
packages/system/src/styles/init.css

- minimap styling from props now works as expected
- fixed svg styles to remove unnecessary spacing
- fixed mask-stroke-width scaling with zoom level

fixed minimap styling by props & mask-stroke-width

---

.changeset/nice-peaches-sit.md
packages/core/src/components/Edges/wrapEdge.tsx

fix(edge-marker): use quotes for marker urls to support css vars 

---

packages/system/src/utils/shallow-node-data.ts

When passing invalid(or unavailable) node id to `useNodesData` it  return `null` which leads to a cash due to missing null check inside custom equality function.
Add null check inside equality function - `shallowNodeData`.

fix(useNodesData): fix crash when passing invalid node id

---

.changeset/giant-waves-boil.md
.changeset/heavy-hairs-decide.md
.changeset/kind-rings-smash.md
.changeset/nice-peaches-sit.md
.changeset/quiet-squids-sort.md
.changeset/serious-socks-yawn.md
.changeset/silent-years-explain.md
examples/vite-app/src/examples/FloatingEdges/FloatingConnectionLine.tsx
examples/vite-app/src/examples/FloatingEdges/utils.ts
packages/background/CHANGELOG.md
packages/background/package.json
packages/controls/CHANGELOG.md
packages/controls/package.json
packages/core/CHANGELOG.md
packages/core/package.json
packages/core/src/components/Nodes/wrapNode.tsx
packages/core/src/store/utils.ts
packages/minimap/CHANGELOG.md
packages/minimap/package.json
packages/node-resizer/CHANGELOG.md
packages/node-resizer/package.json
packages/node-toolbar/CHANGELOG.md
packages/node-toolbar/package.json
packages/reactflow/CHANGELOG.md
packages/reactflow/package.json
pnpm-lock.yaml

- adds deprecation warning for `node.parentNode` which is now called `node.parentId`
- fix: re-observe nodes when hidden is toggled #4064
- fix: handle smoothstep edge if center = 0
- `disableKeyboardA11y` now correctly prevents escape/enter key presses for nodes and edges

React Flow 11.11.0

---

packages/system/src/xyminimap/index.ts

Dragging the Minimap is currently not possible on mobile because it is implemented with movementX, movementY parameters that do not exist on touch events. Additionally they [can be quite brittle](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/movementX).
Fixes #4134 
Possibly fixes #4080

Minimap: removed usage of movementX, movementY and instead calculate delta manually

---

examples/react/src/examples/UseNodesInit/index.tsx
packages/react/src/hooks/useReactFlow.ts
packages/react/src/store/index.ts
packages/react/src/utils/changes.ts
packages/system/src/utils/graph.ts

This PR makes sure that we are always working with `triggerNodeChanges` which works with default nodes and controlled nodes. In the previous version we used `onNodesChange` directly which led to outdated default nodes and related hooks.

fix(react): default node updates closes #4202

---

packages/svelte/src/lib/components/NodeSelection/NodeSelection.svelte
packages/svelte/src/lib/components/NodeWrapper/NodeWrapper.svelte
packages/svelte/src/lib/types/nodes.ts
packages/svelte/src/lib/utils/index.ts

Using `createEventDispatcher` from another imported function seems to break the svelte types and thus none of the node events where typed.
This PR fixes the issue by sharing only the types and not a create function. The `NodeEventMap` type was placed in the types directory to be accessible for both `NodeWrapper` and `NodeSelection`.
I noticed this when upgrading past 0.0.40 were there was a breaking change but no type errors to alert me were and what the new types were

Svelte: Fix Node event types

---

packages/svelte/src/lib/components/Handle/Handle.svelte

I have no idea about `isTarget` but my handles can change dynamically, including their IDs. Anyway I think it's best if anything that depends on a property reacts to changes to that property.
I've confirmed that the change works for me and my dynamic handles.

[SvelteFlow] Make handleId and isTarget reactive

---

packages/svelte/src/lib/components/Handle/Handle.svelte
packages/svelte/src/lib/types/general.ts

Added possibility to overwrite global isValidConnection on each Handle
closes #4133

Svelte: isValidConnection on <Handle />

---

examples/react/src/examples/AddNodeOnEdgeDrop/index.tsx
examples/react/src/examples/Redux/index.tsx
examples/react/src/examples/UseHandleConnections/MultiHandleNode.tsx
examples/react/src/examples/UseHandleConnections/SingleHandleNode.tsx
packages/react/CHANGELOG.md
packages/react/package.json
packages/react/src/components/Handle/index.tsx
packages/react/src/container/GraphView/index.tsx
packages/react/src/container/GraphView/useNodeOrEdgeTypesWarning.ts
packages/react/src/container/GraphView/useStylesLoadedWarning.ts
packages/react/src/index.ts
packages/react/src/utils/general.ts
packages/svelte/CHANGELOG.md
packages/svelte/package.json
packages/svelte/src/lib/components/Handle/Handle.svelte
packages/svelte/src/lib/components/NodeSelection/NodeSelection.svelte
packages/svelte/src/lib/index.ts
packages/svelte/src/lib/plugins/Minimap/Minimap.svelte
packages/svelte/src/lib/plugins/NodeToolbar/NodeToolbar.svelte
packages/svelte/src/lib/types/general.ts
packages/system/package.json
packages/system/src/constants.ts
packages/system/src/types/handles.ts
packages/system/src/utils/store.ts

- don't show nodeTypes warning if not necessary #3923
- add node resizer styles to base.css
- remove `type HandleComponentProps`, only export `type HandleProps`
- add warning when styles not loaded #4047

React Flow 12.0.0-next.18

---

packages/system/src/utils/general.ts

This PR fixes a bug in the `evaluateAbsolutePosition` function where the incorrect parent node was being retrieved from the `nodeLookup` in each iteration of the while loop.
- Modified the line `const parent = nodeLookup.get(parentId);` to `const parent = nodeLookup.get(nextParentId);`.
The original implementation used `parentId` to look up the parent node, which did not change within the loop. This resulted in the same parent node being used for each iteration, leading to incorrect calculations of the absolute position. By using `nextParentId`, we ensure that the correct parent node is retrieved and used in each iteration.

fix: Correct parent node lookup in evaluateAbsolutePosition

---

examples/react/src/App/routes.ts
examples/react/src/examples/ReconnectEdge/index.tsx
examples/react/src/examples/Undirectional/index.tsx
examples/react/src/examples/Validation/index.tsx
examples/react/src/generic-tests/edges/general.ts
examples/svelte/src/generic-tests/edges/general.ts
packages/react/CHANGELOG.md
packages/react/src/components/EdgeWrapper/EdgeUpdateAnchors.tsx
packages/react/src/components/EdgeWrapper/index.tsx
packages/react/src/components/StoreUpdater/index.tsx
packages/react/src/container/EdgeRenderer/index.tsx
packages/react/src/container/GraphView/index.tsx
packages/react/src/container/ReactFlow/index.tsx
packages/react/src/index.ts
packages/react/src/store/initialState.ts
packages/react/src/types/component-props.ts
packages/react/src/types/edges.ts
packages/react/src/types/store.ts
packages/svelte/src/lib/index.ts
packages/system/src/utils/edges/general.ts
packages/system/src/xyhandle/XYHandle.ts

This PR renames:
`updateEdge` => `reconnectEdge`
`onEdgeUpdateStart` => `onReconnectStart`
`onEdgeUpdate` => `onReconnect`
`onEdgeUpdateEnd` => `onReconnectEnd`
`edgeUpdaterRadius` => `reconnectRadius`
`edge.updatable` => `edge.reconnectable`
closes #4346

Rename `updateEdge` to `reconnectEdge`

---

packages/svelte/src/lib/container/Zoom/Zoom.svelte

Svelte: Only prevent shift scrolling when selection is actually in progress

---

.changeset/cool-falcons-argue.md
examples/vite-app/src/examples/Undirectional/index.tsx
examples/vite-app/src/examples/UpdatableEdge/index.tsx
examples/vite-app/src/examples/Validation/index.tsx
packages/core/src/components/Edges/wrapEdge.tsx
packages/core/src/components/Handle/handler.ts
packages/core/src/container/EdgeRenderer/index.tsx
packages/core/src/container/GraphView/index.tsx
packages/core/src/container/ReactFlow/index.tsx
packages/core/src/index.ts
packages/core/src/types/component-props.ts
packages/core/src/types/edges.ts
packages/core/src/types/general.ts
packages/core/src/utils/graph.ts

This PR renames:
updateEdge => reconnectEdge
onEdgeUpdateStart => onReconnectStart
onEdgeUpdate => onReconnect
onEdgeUpdateEnd => onReconnectEnd
edgeUpdaterRadius => reconnectRadius
edge.updatable => edge.reconnectable
and depracates the renamed functions and attributes.

refactor(core): rename updateEdge to reconnectEdge

---

.changeset/cool-falcons-argue.md
.changeset/smooth-news-promise.md
examples/vite-app/src/examples/Undirectional/index.tsx
examples/vite-app/src/examples/UpdatableEdge/index.tsx
examples/vite-app/src/examples/Validation/index.tsx
packages/background/CHANGELOG.md
packages/background/package.json
packages/controls/CHANGELOG.md
packages/controls/package.json
packages/core/CHANGELOG.md
packages/core/package.json
packages/core/src/components/Edges/wrapEdge.tsx
packages/core/src/components/Handle/handler.ts
packages/core/src/container/EdgeRenderer/index.tsx
packages/core/src/container/GraphView/index.tsx
packages/core/src/container/ReactFlow/index.tsx
packages/core/src/hooks/useDrag/index.ts
packages/core/src/index.ts
packages/core/src/types/component-props.ts
packages/core/src/types/edges.ts
packages/core/src/types/general.ts
packages/core/src/utils/graph.ts
packages/minimap/CHANGELOG.md
packages/minimap/package.json
packages/node-resizer/CHANGELOG.md
packages/node-resizer/package.json
packages/node-toolbar/CHANGELOG.md
packages/node-toolbar/package.json
packages/reactflow/CHANGELOG.md
packages/reactflow/package.json

This PR adds some deprecation warnings and introduces new function and attribute names for "edge update" which is now called "edge reconnect": 
`updateEdge` => `reconnectEdge`
`onEdgeUpdateStart` => `onReconnectStart`
`onEdgeUpdate` => `onReconnect`
`onEdgeUpdateEnd` => `onReconnectEnd`
`edgeUpdaterRadius` => `reconnectRadius`
`edge.updatable` => `edge.reconnectable`
We changed the term, because we think it's more clear what it does and is better to distinguish from the new `updateEdge` and `updateEdgeData` helpers in React Flow 12.
- abort drag when multiple touches are detected
- rename updateEdge to reconnectEdge and deprecate function and attribute names

React Flow 11.11.4

---

examples/react/src/App/routes.ts
examples/react/src/examples/ClickDistance/index.tsx
packages/react/CHANGELOG.md
packages/react/package.json
packages/react/src/components/StoreUpdater/index.tsx
packages/react/src/container/FlowRenderer/index.tsx
packages/react/src/container/GraphView/index.tsx
packages/react/src/container/ReactFlow/index.tsx
packages/react/src/container/ZoomPane/index.tsx
packages/react/src/store/index.ts
packages/react/src/types/component-props.ts
packages/react/src/types/store.ts
packages/svelte/CHANGELOG.md
packages/svelte/package.json
packages/svelte/src/lib/actions/zoom/index.ts
packages/svelte/src/lib/container/SvelteFlow/SvelteFlow.svelte
packages/svelte/src/lib/container/SvelteFlow/types.ts
packages/svelte/src/lib/container/SvelteFlow/utils.ts
packages/svelte/src/lib/container/Zoom/Zoom.svelte
packages/svelte/src/lib/container/Zoom/types.ts
packages/svelte/src/lib/store/index.ts
packages/svelte/src/lib/store/types.ts
packages/system/package.json
packages/system/src/types/panzoom.ts
packages/system/src/xydrag/XYDrag.ts
packages/system/src/xydrag/utils.ts
packages/system/src/xypanzoom/XYPanZoom.ts

- add `paneDistanceClick` prop (max distance between mousedown/up that will trigger a click)
- returned nodes in `onNodeDragStop` are set to `dragging=false` 
- add `paneDistanceClick` prop (max distance between mousedown/up that will trigger a click)
- returned nodes in `on:nodedragstop` are set to `dragging=false`

React Flow 12.0.0-next.28 and Svelte Flow 0.1.10

---

packages/react/src/additional-components/Background/Background.tsx
packages/react/src/additional-components/Background/types.ts

First of all, thank you so much to the xyflow team for maintaining this incredible library - it really is a joy to develop with!
I recently discovered a peculiarity with the `offset` prop on the `Background` component. I made a [discussion post](https://github.com/xyflow/xyflow/discussions/4472) about it, but no one has answered my question, which is about a pretty niche feature anyways, so I went ahead with proposing the code changes that make sense to me. 
The documentation regarding the `offset` prop doesn't say anything about the intended purpose/use of this prop. To me, offset makes sense as "translation" or "shift" or similar. And indeed the code has something to do with translation:
```
patternTransform={`translate(-${patternOffset[0]},-${patternOffset[1]})`}
```
However, the …

Control background pattern translation with offset

---

.changeset/curly-llamas-obey.md
packages/svelte/src/lib/components/Handle/Handle.svelte

- Renamed `isConnectable` prop locally to `isConnectableProp` to avoid naming collision with derived var `isConnectable`
- Apparently naming it the same thing as the prop just causes the cmp to prefer the prop instead of the local variable (Peter would know more about this though)

fix(svelte): rename `isConnectable` to `handleConnectable`

---

.changeset/tidy-swans-clap.md
packages/system/src/utils/graph.ts

closes #4516 
Rearranged some code for readability but only 1 line changes from 
```js
const notInitialized = width === null || height === null;
```
to
```js
const forceInitialRender = !node.internals.handleBounds;
```

fix(onlyRenderVisible) render nodes with fixed width & height intially

---

.changeset/curly-cows-repeat.md
.changeset/cyan-frogs-lick.md
packages/svelte/src/lib/store/index.ts
packages/system/src/utils/store.ts

Currently initial fitView is broken for nodeOrigins other than [0,0] (!!!)
A nice side effect of this is that fitView now also respects any clamped positions based on extent.

Update absolute positions before initial fitView

---

.changeset/famous-lobsters-ring.md
packages/react/package.json
packages/system/package.json

This PR follows up on what was done at https://github.com/xyflow/xyflow/pull/4755.
Even having into account the changes in the previous PR, webpack v5 still resolves `@xyflow/react/dist/esm/index.mjs` which then tries to resolve `react/jsx-runtime` within (and in that case it loaded from a .mjs which needs to be `react/jsx-runtime.js`).
The changes I'm proposing introduces a more explicit split in the resolution without room for wrong resolves going further.
\cc @peterkogo @moklick

chore(NA): adds explicit browser, node and default exports resolution

---

.changeset/funny-shrimps-remain.md
packages/react/src/components/BatchProvider/useQueue.ts

This pull request includes changes to the `useQueue` hook to fix deadlock due to automatic batching in React.
Details:
* Replaced the `shouldFlush` boolean state with a `serial` state using `BigInt` to avoid deadlock issues with automatic batching.
* Updated the queue creation to increment the `serial` state instead of setting the `shouldFlush` flag.
* Removed unnecessary state flipping logic and simplified the `useIsomorphicLayoutEffect` dependency to only depend on `serial`.
closes #4779 
Related Issues: #4680, maybe #4774
@peterkogo Could you please review this?

Fix deadlock in useQueue

---

.changeset/tall-kids-lick.md
packages/react/src/container/EdgeRenderer/index.tsx

closes #4867
Second try.
Checked and it works flawlessly with `onlyRenderVisible`. The selector inside `getVisibleEdgeIds` already does everything right.

Fix unneccessary rerenders of edges on viewport resize

---

.changeset/brown-pugs-pump.md
packages/system/src/utils/dom.ts

`event.composedPath` and `event.target` do not always return `HTMLElement` object(as their types suggested).
> [Element](https://developer.mozilla.org/en-US/docs/Web/API/Element), and its children, as well as [Document](https://developer.mozilla.org/en-US/docs/Web/API/Document) and [Window](https://developer.mozilla.org/en-US/docs/Web/API/Window), are the most common event targets
This PR prevents exception from being thrown when the object is not an `HTMLElement` (e.g., a `window`).

fix(system): safely handles non-html-element object

---

.changeset/little-toys-brake.md
examples/react/src/examples/AddNodeOnEdgeDrop/index.tsx
examples/svelte/src/routes/examples/add-node-on-drop/Flow.svelte
packages/react/src/components/Handle/index.tsx
packages/react/src/container/Pane/index.tsx
packages/svelte/src/lib/container/Pane/Pane.svelte
packages/system/src/utils/dom.ts
packages/system/src/xydrag/XYDrag.ts
packages/system/src/xydrag/utils.ts
packages/system/src/xyhandle/XYHandle.ts

Sorry I missed one part in the previous PR #4874.
https://github.com/xyflow/xyflow/blob/0f21ec21ebf01567ec1de4fad1d0c55f40db3463/packages/system/src/utils/dom.ts#L46
This PR adds type checks for all `event.target`.

Fix type check for all event targets

---

.changeset/afraid-trains-hunt.md
packages/svelte/src/lib/plugins/Controls/ControlButton.svelte

I'm guessing the props accidentally had the export keywords removed.  This probably isn't caught by Typescript or CI because the props are passed in by a spread prop from the parent `Controls.svelte`.
Should just be a band-aid fix until the Svelte 5 release is ready to use the `$props` rune.

expose ControlButton props to consumers

---

.changeset/serious-ducks-care.md
packages/system/src/xydrag/XYDrag.ts

This PR ensures that auto-panning is disabled if the `autoPanOnNodeDrag` state changes while dragging on the canvas. Currently, if this property is set to `true` before the drag event starts, the auto-panning logic will begin but won't stop until dragging ends.
In my use case, I'd like to stop auto-panning if I detect that a user has dragged a node over a specific area near the canvas edge.
Feel free to close this PR if this behavior is expected.

fix(system): ensure auto-pan stops when state changes during drag

---

.changeset/cyan-pianos-lie.md
.changeset/sour-jobs-fold.md
packages/react/src/container/ReactFlow/index.tsx

Fixes #4667, #3483
When a node outside the viewport is focused (e.g. via tab or when typing in a previously selected input field), the browser automatically scrolls `rf_wrapper` to bring the node into view, breaking the viewport.
This PR undos that behavior, keeping the viewport stable.

Fix viewport shifting on node focus

---

.changeset/happy-hats-lay.md
packages/react/src/components/ConnectionLine/index.tsx
packages/react/src/types/component-props.ts

The `connectionLineComponent` attribute in `ReactFlowProps` is of type `ConnectionLineComponent` which is a generic type that takes a `NodeType` as a type argument.
The `NodeType` of the `ReactFlowProps` is not getting passed through to the `ConnectionLineComponent`, though. This PR fixes that.
Successfully ran `pnpm build` and `pnpm dev` locally without errors. Also ran `pnpm test:react` and all tests pass except one (but I think it may be flakey - see below).
Small note for the xyflow team: I ran into a few issues running `pnpm test:react`. First, I had trouble running the tests at all because the correct playwright binaries were not installed by default. To install the correct binaries I had to do:
```
cd tests/playwright
pnpm exec playwright install --with-deps
```
I think this is …

Pass through NodeType to connectionLineComponent ReactFlow prop

---

packages/react/src/hooks/useNodeConnections.ts

Fixed a docs typo on https://github.com/xyflow/web/commit/fd6c1a86803003eeec140c772f29a40496fd2991 and noticed we had the same issue in here.

docs(useNodeConnections): fix docs typo

---

packages/react/src/hooks/useKeyPress.ts

Wow you have some complex keypress handling code! 😅 
I bring up a node search bar when `/` is pressed. The XYFlow keydown handler first registers that `/` has been pressed. Then we jump to the node search bar. Then the XYFlow keyup handler runs. The keyup handler sees that we are now inside an input, so it returns early. Leaving `/` forever pressed in the eyes of XYFlow.
This is a niche case and I'm probably the only one hurt. But the fix is so simple. Why would we ignore a key getting released because of being inside an input or whatever the modifier keys are doing? If it's released it's released.
Thanks for considering this!

Always allow releasing keys

---

.changeset/hungry-shrimps-remain.md
.changeset/poor-poems-visit.md
examples/react/package.json
examples/react/src/examples/Basic/index.tsx
examples/react/src/examples/Stress/index.tsx
examples/svelte/package.json
examples/svelte/src/routes/examples/overview/+page.svelte
package.json
packages/react/package.json
packages/react/src/components/StoreUpdater/index.tsx
packages/react/src/hooks/useReactFlow.ts
packages/react/src/hooks/useViewportHelper.ts
packages/react/src/store/index.ts
packages/react/src/store/initialState.ts
packages/react/src/types/general.ts
packages/react/src/types/instance.ts
packages/react/src/types/store.ts
packages/svelte/package.json
packages/svelte/src/lib/container/SvelteFlow/SvelteFlow.svelte
packages/svelte/src/lib/store/index.ts
packages/svelte/src/lib/store/initial-store.ts
packages/svelte/src/lib/store/utils.ts
packages/system/package.json
packages/system/src/utils/graph.ts
packages/system/src/utils/store.ts
pnpm-lock.yaml
tests/playwright/e2e/pane.spec.ts
tooling/rollup-config/package.json

- `fitViewOnInit`, `fitViewOnInitDone` and `fitViewInitOptions` from store
- `fitView` and `fitViewSync` from store actions
- Handling initial `fitView` in updateNodeInternals
- `fitView` from `useViewportHelper`
- `fitViewQueued`, `fitViewOptions` and `fitViewResolver` to store
- `adoptUserNodes` now returns nodesInitialized
- `fitViewQueued` is now handled directly after `adoptUserNodes`
- `fitView` from `useReactFlow` now only sets `fitViewQueued` in the store and triggers `setNodes` without any changes via the `batchProvider` to trigger adoptUserNodes
- Promise resolution now works via `fitViewResolver`, which is a [`Promise.withResolvers`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/withResolvers). Even though this is a Baseline 2024 …

Enhance fitView

---

.changeset/fifty-lizards-smash.md
packages/react/src/index.ts
packages/svelte/src/lib/index.ts

Missing the NodeConnection type export for the new hook `useNodeConnections`. 
I mainly use React, and doing guesswork on the Svelte part.

chore: add missing type re-export for NodeConnection

---

.changeset/rotten-news-deliver.md
packages/react/src/additional-components/MiniMap/MiniMap.tsx

his ts type is `number`, i think this comparison was a mistake

fix: compare `nodeStrokeWidth` with `number`, not with `string`

---

.changeset/eighty-foxes-add.md
packages/react/src/types/edges.ts

added description for markerStart/markerEnd like currently on reactflow website https://reactflow.dev/api-reference/components/base-edge#marker-start

Improve TSDoc comments for `BaseEdgeProps`

---

.changeset/serious-jeans-tap.md
packages/system/src/styles/style.css

I found a small styling issue while creating a Reactflow component in our application. See discussion: https://github.com/xyflow/xyflow/discussions/5152
With the proposed change, horizontal buttons would have no bottom border by default.
closes #5152

When horizontal, remove the border from all control buttons

---

CONTRIBUTING.md

Reviewing the contributing guide, a few of the links were outdated. Links going to the old wbkd url were redirecting, but I updated those as well.

docs(CONTRIBUTING): update links

---

.changeset/nine-crabs-help.md
packages/svelte/src/lib/components/A11yDescriptions/A11yDescriptions.svelte

In some environments, inline styles are not permitted due to security issues (e.g. strict CSP). The a11y messages will be visible in these environments due to browsers blocking inline styles.
Change the inline styles to use classes instead.

refactor(svelte): change a11y inline styles to classes

---

examples/react/src/examples/A11y/index.tsx

Removes the `ariaRoleDescription` field we caught earlier. It's already removed everywhere else.

fix(a11y): remove outdated `ariaRoleDescription` field

---

packages/react/src/types/edges.ts
packages/svelte/src/lib/types/edges.ts

From this issue in the web repo: https://github.com/xyflow/web/issues/477
I think the best place to update this is inside the api-reference. It seemed too specific to put in the example pages.

docs(edges): update marker documentation to include formatting info

---

examples/react/src/App/header.tsx

- The dropdown now **correctly reflects the current example after a page refresh**.
- Achieved by **parsing the example name from the URL** and using it to initialize the dropdown state.
- Added an `aria-label` to the dropdown for **improved accessibility**.

feat(examples): sync dropdown with current example on refresh

---

.changeset/dry-timers-build.md
.changeset/smooth-stingrays-play.md
packages/react/src/additional-components/MiniMap/index.tsx
packages/svelte/src/lib/plugins/Minimap/index.ts

It's already possible to use a custom `nodeComponent`, this enables the users to used the original `MiniMapNode` with a custom wrapper

Export MiniMapNode

---

.changeset/funny-doors-travel.md
examples/react/src/App/routes.ts
examples/react/src/examples/DetachedHandle/index.tsx
examples/react/src/examples/DetachedHandle/style.css
examples/svelte/src/components/Header/Header.svelte
examples/svelte/src/routes/examples/detached-handle/+page.svelte
examples/svelte/src/routes/examples/detached-handle/CustomNode.svelte
packages/react/src/components/EdgeWrapper/EdgeUpdateAnchors.tsx
packages/react/src/components/Handle/index.tsx
packages/svelte/src/lib/components/EdgeReconnectAnchor/EdgeReconnectAnchor.svelte
packages/svelte/src/lib/components/Handle/Handle.svelte
packages/system/src/xyhandle/XYHandle.ts
packages/system/src/xyhandle/types.ts

This change enables having detached elements (outside the handle's bounding box) in handles which will still trigger edge connections.

Allow detached handles 

---

.changeset/stupid-lizards-wash.md
.changeset/wet-beds-greet.md
examples/react/src/examples/Basic/index.tsx
examples/svelte/src/routes/examples/overview/Flow.svelte
packages/react/src/hooks/useResizeHandler.ts
packages/svelte/src/lib/container/SvelteFlow/Wrapper.svelte

Prevent unnecessary resize calculations and error messages for invisible elements by checking visibility before processing dimensions.
We use `display:none` in our project to hide a react flow canvas on demand without unmounting or destroying its internal states. This patch prevents unnecessary calculations, and also suppresses the "The React Flow parent container needs a width and a height to render the graph." error message in this case.

fix: skip resize handler updates when DOM node is not visible

---

.changeset/curly-steaks-check.md
packages/react/src/types/edges.ts

Adds the `type` property to `EdgeProps` to match `NodeProps` behavior. This allows custom edge components to access their edge type with proper TypeScript support.
The `type` property was already being passed [at runtime in `EdgeWrapper`](https://github.com/xyflow/xyflow/blob/4c2a3030575557b8270575e88fa5366bc6e1b476/packages/react/src/components/EdgeWrapper/index.tsx#L217) but was missing from the TypeScript type definition.

fix(edges): add `type` property to `EdgeProps`
